// Auto-generated GPA score landing-page data table.
// One entry per GPA score (e.g. 3.8). Keys are dash slugs ("3-8").
// Source for tier rankings: NCES, College Board, US News admit-rate brackets.

export interface GpaScoreData {
  slug: string;             // "3-8" → URL /gpa/3-8
  value: string;            // "3.8"
  numeric: number;          // 3.8
  letter: string;           // "A-/A"
  percentage: string;       // "90-92%" range
  percentile: string;       // "Top 15% of high schoolers"
  verdict: string;          // 1-line plain-language verdict
  verdictLong: string;      // 2-3 sentence elaboration
  collegeTier: string;      // tier of schools accessible
  ivyChance: string;        // "Stretch" | "Reach" | "Match" etc
  stateFlagshipChance: string;
  scholarshipImpact: string;
  isGood: "yes" | "good" | "average" | "low" | "very-low";
  primaryKw: string;        // main target keyword (highest vol)
  searchVolume: number;     // monthly US volume from Ahrefs
  faqs: { q: string; a: string }[];
  // Wave-3 enrichment. Pages without `intro` get noindex + drop from sitemap.
  indexed?: boolean;
  intro?: string;           // 60-120 word score-specific opening
  realWorldExample?: string; // 2-3 sentence anonymized student example
  uniqueTips?: string[];    // 3-4 score-specific tips replacing the recovery/maintain bullets
  sourceUrl?: string;       // citation (NCES / College Board / IPEDS)
}

export const GPA_SCORE_DATA: GpaScoreData[] = [
  {
    slug: "1-0",
    value: "1.0",
    numeric: 1.0,
    letter: "D",
    percentage: "65%",
    percentile: "Bottom 5% of US high schoolers",
    verdict: "A 1.0 GPA is a D average — it's failing for most college and scholarship requirements.",
    verdictLong: "A 1.0 GPA equals straight D's on the 4.0 scale, putting you in the bottom 5% nationally. Most colleges, including community colleges, require at least a 2.0 cumulative GPA. Without intervention, students at this level often face academic dismissal or are pushed onto probation.",
    collegeTier: "Open-enrollment community colleges only, often with mandatory remedial coursework",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Disqualifies you from virtually all merit aid. Federal Pell Grant still available based on financial need.",
    isGood: "very-low",
    primaryKw: "1.0 gpa",
    searchVolume: 800,
    faqs: [
      { q: "Is a 1.0 GPA passing?", a: "A 1.0 GPA equals a D average. Technically a D is the lowest passing grade at most schools — but it usually does not meet course prerequisites or graduation requirements." },
      { q: "Can I raise a 1.0 GPA?", a: "Yes, but it requires earning A's in nearly every remaining class. Use the GPA Goal Calculator to see what's mathematically possible based on your credits earned and remaining." },
      { q: "What colleges accept a 1.0 GPA?", a: "Most four-year colleges require 2.0+. Open-enrollment community colleges sometimes admit students below 2.0 but place them in developmental courses first." },
    ],
  },
  {
    slug: "1-3",
    value: "1.3",
    numeric: 1.3,
    letter: "D+",
    percentage: "67-69%",
    percentile: "Bottom 7% of US high schoolers",
    verdict: "A 1.3 GPA is a D+ average — below the threshold to graduate from many high schools.",
    verdictLong: "A 1.3 GPA sits at D+ on the 4.0 scale. Most US high schools require at least a 2.0 to graduate, and four-year colleges almost always require 2.5+. At this level the focus should be on stopping the decline, then earning A's to lift the cumulative average.",
    collegeTier: "Community colleges with remedial pathways",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Disqualifies all merit aid. Need-based federal aid still available.",
    isGood: "very-low",
    primaryKw: "1.3 gpa",
    searchVolume: 500,
    faqs: [
      { q: "Is a 1.3 GPA recoverable?", a: "Yes, especially early in your academic career. The fewer credits you've earned, the easier each new grade moves the average. Check the math with our GPA Goal Calculator." },
      { q: "Will a 1.3 GPA keep me from graduating?", a: "Most US high schools require a 2.0 GPA to graduate. A 1.3 will not meet that bar — you'll need to raise it or enter a credit-recovery program." },
    ],
  },
  {
    slug: "1-7",
    value: "1.7",
    numeric: 1.7,
    letter: "C-",
    percentage: "70-72%",
    percentile: "Bottom 10% of US high schoolers",
    verdict: "A 1.7 GPA is a C- average — usually below the graduation threshold and almost all college admit minimums.",
    verdictLong: "A 1.7 GPA equates to a C- letter grade. While technically passing, it sits below the 2.0 minimum that most high schools require for graduation and that nearly every four-year college requires for admission.",
    collegeTier: "Community colleges, some open-enrollment four-years",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Most merit awards require 2.5+. Federal Pell Grant available regardless of GPA.",
    isGood: "low",
    primaryKw: "1.7 gpa",
    searchVolume: 800,
    faqs: [
      { q: "Can I get into college with a 1.7 GPA?", a: "Open-enrollment community colleges admit students at this level, often with developmental course placement. Selective four-year colleges typically require 2.5 or higher." },
      { q: "What's the fastest way to raise a 1.7 GPA?", a: "Three things matter: stop the decline, retake courses where your school allows grade replacement, and load up on courses you can confidently earn A's in." },
    ],
  },
  {
    slug: "1-8",
    value: "1.8",
    numeric: 1.8,
    letter: "C-",
    percentage: "72-73%",
    percentile: "Bottom 11% of US high schoolers",
    verdict: "A 1.8 GPA is a low C- — under the 2.0 floor most schools require to graduate or transfer.",
    verdictLong: "A 1.8 GPA falls in the C- range. It's only 0.2 points below the 2.0 minimum required by most high schools and four-year colleges, so a recovery is plausible with focused effort.",
    collegeTier: "Community colleges and some less-selective four-year schools",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Most scholarships require 2.5+ minimum. Pell Grant still based on need only.",
    isGood: "low",
    primaryKw: "1.8 gpa",
    searchVolume: 900,
    faqs: [
      { q: "Is a 1.8 GPA enough to graduate high school?", a: "Most US high schools require a 2.0 cumulative GPA to graduate. A 1.8 would typically need to be raised first." },
      { q: "How many A's do I need to raise a 1.8 GPA?", a: "Depends on how many credits you've already earned. Run the math on the GPA Goal Calculator with your current credits and target." },
    ],
  },
  {
    slug: "1-9",
    value: "1.9",
    numeric: 1.9,
    letter: "C-/C",
    percentage: "73-74%",
    percentile: "Bottom 13% of US high schoolers",
    verdict: "A 1.9 GPA is just below the standard 2.0 floor required by most colleges and many high schools.",
    verdictLong: "A 1.9 GPA equates to a low C. You're one-tenth of a point below the 2.0 cutoff that most high schools require for graduation and that almost all four-year colleges set as their minimum.",
    collegeTier: "Community colleges, some less-selective four-years",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Below most merit-aid thresholds (typically 2.5+). Need-based aid unaffected.",
    isGood: "low",
    primaryKw: "1.9 gpa",
    searchVolume: 800,
    faqs: [
      { q: "Can a 1.9 GPA become a 2.0 quickly?", a: "Yes — one strong semester of A's and B's can lift a 1.9 above 2.0, especially with fewer total credits earned. The exact number depends on your transcript size." },
    ],
  },
  {
    slug: "2-0",
    value: "2.0",
    numeric: 2.0,
    letter: "C",
    percentage: "73-76%",
    percentile: "Bottom 20% of US high schoolers",
    verdict: "A 2.0 GPA is a straight C average — the bare minimum to graduate high school and apply to college.",
    verdictLong: "A 2.0 GPA equals a C average and is the standard graduation requirement at most US high schools. It meets the minimum admission bar at most community colleges and a handful of four-year schools, but selective colleges and most merit scholarships expect higher.",
    collegeTier: "Community colleges, less-selective four-years, some state schools with conditional admit",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Doesn't meet most merit thresholds (typically 2.5-3.0+). Need-based aid available.",
    isGood: "low",
    primaryKw: "2.0 gpa",
    searchVolume: 4700,
    faqs: [
      { q: "Is a 2.0 GPA failing?", a: "No. A 2.0 GPA is a C average and is generally considered the minimum passing GPA for high school graduation and many college admission requirements." },
      { q: "Can I go to a 4-year college with a 2.0 GPA?", a: "Some less-selective four-year schools admit students at the 2.0 level. Most state flagships and selective colleges require 3.0 or higher." },
      { q: "What is a 2.0 GPA in percentage?", a: "A 2.0 GPA equates to roughly 73-76% on most US grading scales, equivalent to a C letter grade." },
    ],
  },
  {
    slug: "2-3",
    value: "2.3",
    numeric: 2.3,
    letter: "C+",
    percentage: "77-79%",
    percentile: "Bottom 22% of US high schoolers",
    verdict: "A 2.3 GPA is a C+ average — meets high school graduation requirements but is below the standard for most four-year colleges.",
    verdictLong: "A 2.3 GPA equals a C+ on the 4.0 scale. You're meeting high school graduation requirements but sitting below the 2.5-3.0 minimum that most state and private colleges expect from applicants.",
    collegeTier: "Community colleges, some state non-flagships, regional privates",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not realistic",
    scholarshipImpact: "Doesn't meet 2.5+ minimums for most merit scholarships. Pell and need-based aid available.",
    isGood: "low",
    primaryKw: "2.3 gpa",
    searchVolume: 1900,
    faqs: [
      { q: "Is a 2.3 GPA good?", a: "A 2.3 GPA is a C+ — passing, but below the level that opens up four-year college and scholarship options. Raising to 2.5-3.0 unlocks many more opportunities." },
      { q: "What is a 2.3 GPA?", a: "A 2.3 GPA equals a C+ letter grade, roughly 77-79% on most US grading scales. It meets graduation requirements at most high schools but is below the admit threshold of most four-year colleges." },
    ],
  },
  {
    slug: "2-4",
    value: "2.4",
    numeric: 2.4,
    letter: "C+",
    percentage: "77-79%",
    percentile: "Bottom 23% of US high schoolers",
    verdict: "A 2.4 GPA is a C+ average — usable for community college and some non-selective four-years.",
    verdictLong: "A 2.4 GPA is in the C+ range. It meets graduation requirements, opens up community college admission, and some less-selective four-year schools may accept you with a strong application or upward trend in grades.",
    collegeTier: "Community colleges, non-flagship state schools, some regional privates",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not realistic",
    scholarshipImpact: "Below 2.5 merit threshold. Need-based aid available.",
    isGood: "low",
    primaryKw: "2.4 gpa letter grade",
    searchVolume: 500,
    faqs: [
      { q: "What letter grade is a 2.4 GPA?", a: "A 2.4 GPA equals a C+ letter grade on the standard 4.0 scale used by most US high schools and colleges." },
    ],
  },
  {
    slug: "2-5",
    value: "2.5",
    numeric: 2.5,
    letter: "B-/C+",
    percentage: "80-82%",
    percentile: "Bottom 25% of US high schoolers",
    verdict: "A 2.5 GPA is just at the B- line — meets the bar for many state colleges and basic merit awards.",
    verdictLong: "A 2.5 GPA equals a B-/C+ average. It crosses the threshold used by many state colleges for unconditional admission and the minimum for many institutional merit scholarships.",
    collegeTier: "Most state universities, community colleges, regional private colleges",
    ivyChance: "Not possible",
    stateFlagshipChance: "Below typical admit, possible with strong essays/extracurriculars",
    scholarshipImpact: "Meets the 2.5 floor for many basic merit awards.",
    isGood: "average",
    primaryKw: "2.5 gpa",
    searchVolume: 4300,
    faqs: [
      { q: "Is a 2.5 GPA good?", a: "A 2.5 GPA is the standard B- floor — it meets minimum admission at most state colleges and basic merit-aid thresholds, but it's below the 3.0+ that competitive programs expect." },
      { q: "What letter grade is a 2.5 GPA?", a: "A 2.5 GPA sits between C+ and B-, equivalent to roughly 80-82% on most US grading scales." },
      { q: "What is a 2.5 GPA in percentage?", a: "A 2.5 GPA equals approximately 80-82% on US grading scales — a low B-." },
    ],
    indexed: true,
    intro:
      "A 2.5 GPA — roughly a C+ average — sits below the US high school median and disqualifies you from most state-flagship direct admission and merit scholarship eligibility. It's not catastrophic: community college admission is unaffected, and a strong CC GPA can rebuild your record for transfer in two years. But four-year direct admission usually requires an upward trend (clear junior/senior improvement), a meaningful extracurricular signal, or a community-college transfer pathway.",
    realWorldExample:
      "A 2.5 cumulative GPA puts you in roughly the bottom 25-30% of US high school graduates. NCES data shows about 15% of US high school grads finish with cumulative GPAs below 2.75 — the band where most academic recovery work happens.",
    uniqueTips: [
      "<strong class=\"text-slate-900\">Community college transfer is the wide-open path.</strong> A 3.0+ GPA across your first year of CC (typically 30 credits) qualifies you for guaranteed transfer to most state flagships under articulation agreements — including UCF, ASU, and most UC system schools.",
      "<strong class=\"text-slate-900\">Federal Pell Grant requires only 2.0.</strong> Pell eligibility uses the school's Satisfactory Academic Progress (SAP) floor, which is almost always 2.0 — not 2.5. You're well clear of Pell disqualification at a 2.5.",
      "<strong class=\"text-slate-900\">NCAA D1 eligibility cuts at 2.3 core GPA.</strong> At a 2.5 you qualify, but you're on the NCAA sliding scale — the lower your core GPA, the higher your SAT/ACT must be. At 2.5 the floor is SAT 1010+ or ACT 19+ to be a qualifier.",
      "<strong class=\"text-slate-900\">Grade replacement is the fastest GPA lift.</strong> If your school allows retake-with-replacement for D/F grades, even one or two retakes can push a 2.5 toward 3.0 within two semesters — much faster than slow improvement.",
    ],
    sourceUrl: "https://nces.ed.gov/programs/coe/indicator/cnb",
  },
  {
    slug: "2-6",
    value: "2.6",
    numeric: 2.6,
    letter: "B-",
    percentage: "80-82%",
    percentile: "Bottom 28% of US high schoolers",
    verdict: "A 2.6 GPA is a low B- — opens up state college admissions but is below selective-school cutoffs.",
    verdictLong: "A 2.6 GPA is in the low B- range. It meets the admission bar at most state colleges and many regional private universities. Selective and flagship schools typically expect 3.0 or higher.",
    collegeTier: "Most state universities and regional privates",
    ivyChance: "Not possible",
    stateFlagshipChance: "Below typical, possible with strong upward trend",
    scholarshipImpact: "Meets most institutional 2.5 minimums.",
    isGood: "average",
    primaryKw: "2.6 gpa letter grade",
    searchVolume: 700,
    faqs: [
      { q: "What letter grade is a 2.6 GPA?", a: "A 2.6 GPA equals a B- letter grade, roughly 80-82% on most US grading scales." },
    ],
  },
  {
    slug: "2-7",
    value: "2.7",
    numeric: 2.7,
    letter: "B-",
    percentage: "80-83%",
    percentile: "Bottom 30% of US high schoolers",
    verdict: "A 2.7 GPA is a solid B- — sufficient for most state colleges and many merit-aid thresholds.",
    verdictLong: "A 2.7 GPA is a B- average. It comfortably clears admission at most state schools and many regional private universities, and meets the 2.5+ minimum for most basic merit scholarships.",
    collegeTier: "Most state universities, regional privates, some larger publics",
    ivyChance: "Not possible",
    stateFlagshipChance: "Match for less-selective flagships, below for top flagships",
    scholarshipImpact: "Meets most institutional 2.5+ thresholds.",
    isGood: "average",
    primaryKw: "2.7 gpa",
    searchVolume: 3500,
    faqs: [
      { q: "Is a 2.7 GPA good?", a: "A 2.7 GPA is a B- average — solid for state college admission and most basic merit scholarships. It's below the 3.0+ threshold that more selective schools expect." },
      { q: "What is a 2.7 GPA?", a: "A 2.7 GPA equals a B- letter grade, roughly 80-83% on US grading scales." },
    ],
  },
  {
    slug: "2-8",
    value: "2.8",
    numeric: 2.8,
    letter: "B-",
    percentage: "83-86%",
    percentile: "Bottom 35% of US high schoolers",
    verdict: "A 2.8 GPA is a high B- — opens up most state colleges and unlocks more merit-aid options.",
    verdictLong: "A 2.8 GPA equals a high B-. It opens admission to most state universities, regional privates, and many less-selective flagship state schools. It clears the 2.5 minimum for basic scholarships but falls short of the 3.0+ that competitive merit aid requires.",
    collegeTier: "Most state colleges, regional privates, some less-selective flagships",
    ivyChance: "Not possible",
    stateFlagshipChance: "Match for less-selective flagships",
    scholarshipImpact: "Meets 2.5 floor, just below 3.0 for stronger awards.",
    isGood: "average",
    primaryKw: "2.8 gpa",
    searchVolume: 4300,
    faqs: [
      { q: "Is a 2.8 GPA good?", a: "A 2.8 GPA is a high B- — strong enough for most state college admissions and basic merit scholarships, but below the 3.0+ threshold that competitive programs expect." },
      { q: "Is a 2.8 GPA good in high school?", a: "It's slightly below average for US high schoolers. It's enough to graduate and apply to most state schools, but selective colleges and competitive scholarships typically want 3.0 or higher." },
      { q: "What is a 2.8 GPA in percentage?", a: "A 2.8 GPA equals approximately 83-86% on US grading scales, equivalent to a B- letter grade." },
    ],
  },
  {
    slug: "2-9",
    value: "2.9",
    numeric: 2.9,
    letter: "B-/B",
    percentage: "83-86%",
    percentile: "Bottom 38% of US high schoolers",
    verdict: "A 2.9 GPA is just below the B threshold — within reach of strong scholarships and selective state schools.",
    verdictLong: "A 2.9 GPA is a high B-, just one point below the 3.0 line that many scholarships and selective colleges set as their floor. A strong final semester can push you above it.",
    collegeTier: "Most state colleges, regional privates, some flagships",
    ivyChance: "Not realistic",
    stateFlagshipChance: "Match for less-selective flagships",
    scholarshipImpact: "Just below the 3.0 cutoff for competitive merit aid.",
    isGood: "average",
    primaryKw: "2.9 gpa letter grade",
    searchVolume: 700,
    faqs: [
      { q: "What letter grade is a 2.9 GPA?", a: "A 2.9 GPA is a high B-, equivalent to roughly 83-86% on US grading scales." },
    ],
  },
  {
    slug: "3-0",
    value: "3.0",
    numeric: 3.0,
    letter: "B",
    percentage: "83-86%",
    percentile: "Around average for US high schoolers (50th percentile)",
    verdict: "A 3.0 GPA is a B average — the standard \"good\" GPA that opens up most state colleges and many scholarships.",
    verdictLong: "A 3.0 GPA equals a B average and sits at the national high school median. It's the threshold most state colleges, NCAA athletic eligibility, and many merit scholarships use as their minimum. Selective and elite colleges expect 3.5 or higher.",
    collegeTier: "Most state universities (including some flagships), regional privates, NCAA eligible",
    ivyChance: "Not realistic for top tier",
    stateFlagshipChance: "Match for many state flagships",
    scholarshipImpact: "Meets 3.0 floor used by most institutional merit awards.",
    isGood: "good",
    primaryKw: "3.0 gpa",
    searchVolume: 9300,
    faqs: [
      { q: "Is a 3.0 GPA good?", a: "Yes — a 3.0 GPA is a B average and is generally considered \"good.\" It meets admission requirements at most state colleges and the threshold for most merit-aid programs." },
      { q: "What is a 3.0 GPA in letter grade?", a: "A 3.0 GPA equals a B letter grade on the standard 4.0 scale." },
      { q: "Is a 3.0 GPA good in college?", a: "In college a 3.0 is a B average — solid and above the 2.0 minimum almost all programs require to stay in good standing. For graduate school admission, however, you typically want 3.0-3.5 minimum." },
      { q: "What is a 3.0 GPA in percentage?", a: "A 3.0 GPA equals approximately 83-86% on most US grading scales, equivalent to a B letter grade." },
    ],
    indexed: true,
    intro:
      "A 3.0 GPA — straight B's — sits right at the median for US high schoolers. It's the line between \"fine\" and \"competitive\" depending on context: at a non-selective school you're average, at a competitive private high school you're behind, and at most state flagships you're a borderline candidate. The good news: a 3.0 is enough to keep the doors open at the majority of US four-year colleges, most scholarship programs, and any community-college transfer pathway.",
    realWorldExample:
      "NCES tracks roughly 32% of US high school graduates landing in the 2.75-3.25 cumulative range — the 3.0 mark sits at the upper edge of that median band. The state flagships that publish admit data show roughly 35-50% of admits have unweighted GPAs in the 3.0-3.5 range.",
    uniqueTips: [
      "<strong class=\"text-slate-900\">A 3.0 is mathematically vulnerable.</strong> One C in a 5-credit class can drop you to 2.85, kicking you out of most scholarship renewals (the common floor is 2.75 or 3.0). Aim for a 3.2 cushion to absorb a slip.",
      "<strong class=\"text-slate-900\">Strong CC-to-flagship transfer pathway.</strong> A 3.0 finishing a community college associate's degree makes you a viable transfer to most state systems — Ohio State, Penn State, ASU, and UC Riverside all admit 3.0+ CC transfers regularly.",
      "<strong class=\"text-slate-900\">3.0 is the NHS / ROTC / state-merit floor.</strong> National Honor Society admission, ROTC scholarship eligibility, and renewal for Bright Futures (FL), HOPE (GA), and most state merit awards all use 3.0 as the cutoff. Drop below and the award terminates.",
      "<strong class=\"text-slate-900\">Don't confuse weighted with unweighted.</strong> A weighted 4.2 with an unweighted 3.0 reads to admissions as \"took hard classes, struggled with material.\" Close the gap by aiming for B+ in your AP/Honors load, not just by stacking advanced courses.",
    ],
    sourceUrl: "https://nces.ed.gov/programs/coe/indicator/csb",
  },
  {
    slug: "3-1",
    value: "3.1",
    numeric: 3.1,
    letter: "B",
    percentage: "84-86%",
    percentile: "53rd percentile of US high schoolers",
    verdict: "A 3.1 GPA is a B average — above national median, meets most state college and basic merit-aid thresholds.",
    verdictLong: "A 3.1 GPA is a low-to-mid B. It clears the 3.0 threshold most state colleges and basic merit scholarships use as their minimum, while sitting just above the national high school median.",
    collegeTier: "Most state universities, regional privates, NCAA eligible",
    ivyChance: "Not realistic for top tier",
    stateFlagshipChance: "Match for many state flagships, reach for top flagships",
    scholarshipImpact: "Meets 3.0 floor used by most institutional merit awards.",
    isGood: "good",
    primaryKw: "3.1 gpa",
    searchVolume: 2800,
    faqs: [
      { q: "Is a 3.1 GPA good?", a: "Yes — a 3.1 GPA is a B average and slightly above the national high school median. It meets admission requirements at most state colleges and the 3.0 threshold used by most merit-aid programs." },
      { q: "What is a 3.1 GPA?", a: "A 3.1 GPA equals a B letter grade, roughly 84-86% on most US grading scales." },
    ],
  },
  {
    slug: "3-2",
    value: "3.2",
    numeric: 3.2,
    letter: "B",
    percentage: "84-86%",
    percentile: "57th percentile of US high schoolers",
    verdict: "A 3.2 GPA is a solid B — opens up most state colleges, many private universities, and competitive merit-aid programs.",
    verdictLong: "A 3.2 GPA sits comfortably in the B range. It meets the 3.0+ threshold used by most state colleges, private universities, and basic merit scholarships, while putting you above the US high school median.",
    collegeTier: "Most state colleges including flagships, regional privates, NCAA eligible",
    ivyChance: "Reach (very selective)",
    stateFlagshipChance: "Match for most state flagships",
    scholarshipImpact: "Meets 3.0+ threshold for competitive merit aid.",
    isGood: "good",
    primaryKw: "3.2 gpa letter grade",
    searchVolume: 1200,
    faqs: [
      { q: "What letter grade is a 3.2 GPA?", a: "A 3.2 GPA equals a B letter grade, roughly 84-86% on US grading scales." },
      { q: "Is a 3.2 GPA good in college?", a: "Yes — a 3.2 GPA in college clears the 3.0 floor most graduate schools and competitive scholarships use, while comfortably exceeding the 2.0 minimum required to stay in good academic standing." },
    ],
  },
  {
    slug: "3-3",
    value: "3.3",
    numeric: 3.3,
    letter: "B+",
    percentage: "87-89%",
    percentile: "60th percentile of US high schoolers",
    verdict: "A 3.3 GPA is a B+ average — solid for most state flagships and competitive merit aid.",
    verdictLong: "A 3.3 GPA equals a B+ letter grade. It's above the national high school median and opens up most state flagship universities, many private colleges, and competitive merit scholarship programs.",
    collegeTier: "Most state flagships, regional privates, many mid-tier privates",
    ivyChance: "Reach (very selective)",
    stateFlagshipChance: "Match for most flagships",
    scholarshipImpact: "Meets 3.0+ requirements for competitive merit aid.",
    isGood: "good",
    primaryKw: "3.3 gpa",
    searchVolume: 5500,
    faqs: [
      { q: "Is a 3.3 GPA good?", a: "Yes — a 3.3 GPA is a B+ average and sits comfortably above the national high school median. It opens up most state flagships and meets the threshold for competitive merit aid." },
      { q: "Is 3.3 a good gpa?", a: "Yes. A 3.3 is a B+ — solid for most state flagship universities, competitive scholarships, and many private colleges." },
      { q: "What is a 3.3 GPA in percentage?", a: "A 3.3 GPA equals approximately 87-89% on US grading scales, equivalent to a B+." },
    ],
  },
  {
    slug: "3-4",
    value: "3.4",
    numeric: 3.4,
    letter: "B+",
    percentage: "87-89%",
    percentile: "65th percentile of US high schoolers",
    verdict: "A 3.4 GPA is a high B+ — above national median, opens most state flagships and competitive scholarships.",
    verdictLong: "A 3.4 GPA equals a high B+ letter grade. You're in the top 35% of US high school students. This GPA opens admission to most state flagship universities, many private colleges, and competitive merit-aid programs.",
    collegeTier: "Most state flagships, many private universities, NCAA eligible",
    ivyChance: "Reach",
    stateFlagshipChance: "Match for most flagships",
    scholarshipImpact: "Meets 3.0-3.5 thresholds for stronger institutional merit aid.",
    isGood: "good",
    primaryKw: "3.4 gpa",
    searchVolume: 6400,
    faqs: [
      { q: "Is a 3.4 GPA good?", a: "Yes — a 3.4 GPA is a high B+ and puts you in the top 35% of US high schoolers. It opens up most state flagship universities and competitive merit aid." },
      { q: "Is a 3.4 GPA good in high school?", a: "Yes. A 3.4 in high school is above the national median and well-positioned for state flagship admission. Selective private colleges typically expect 3.7+." },
      { q: "What letter grade is a 3.4 GPA?", a: "A 3.4 GPA equals a B+ letter grade, roughly 87-89% on US grading scales." },
    ],
  },
  {
    slug: "3-5",
    value: "3.5",
    numeric: 3.5,
    letter: "A-",
    percentage: "90-93%",
    percentile: "70th percentile of US high schoolers",
    verdict: "A 3.5 GPA is an A- average — the standard \"dean's list\" GPA and the threshold for many selective colleges.",
    verdictLong: "A 3.5 GPA equals an A- letter grade. It's the dean's list standard at most colleges and the typical admit GPA for less-selective private universities. Many merit scholarships set 3.5 as their minimum threshold.",
    collegeTier: "State flagships, many private universities, public honors colleges, NCAA Division I eligible",
    ivyChance: "Reach",
    stateFlagshipChance: "Strong match",
    scholarshipImpact: "Meets 3.5 threshold for stronger merit aid and most honors program admission.",
    isGood: "good",
    primaryKw: "is a 3.5 gpa good",
    searchVolume: 6100,
    faqs: [
      { q: "Is a 3.5 GPA good?", a: "Yes — a 3.5 GPA is an A- average and considered \"very good.\" It's the dean's list standard and the threshold for many competitive merit scholarships." },
      { q: "Is a 3.5 GPA good in college?", a: "Yes. In college a 3.5 GPA is excellent — it qualifies for dean's list at most schools and clears the bar for most graduate school admissions." },
      { q: "Is a 3.5 GPA good in high school?", a: "Yes. A 3.5 GPA in high school puts you in the top 30% nationally and opens admission to most state flagships and many private universities. Top-tier colleges (Ivies, MIT, Stanford) typically expect 3.8+." },
      { q: "What is a 3.5 GPA?", a: "A 3.5 GPA equals an A- letter grade, roughly 90-93% on US grading scales." },
    ],
    indexed: true,
    intro:
      "A 3.5 GPA puts you in the top 25-30% of US high school graduates and clears the bar for selective state universities, most merit scholarships, and competitive transfer programs. It's where the highest-leverage scholarship dollars get unlocked — full Bright Futures coverage in Florida, in-state honors program admission, NCAA Division I eligibility, ROTC competitive awards. Not yet at the Ivy or top-10 reach level, but the practical floor for most useful college outcomes.",
    realWorldExample:
      "A 3.5 is the floor most state-flagship honors programs use for sophomore admission after a freshman year of college-level work. It's the same number Florida's Bright Futures Academic Scholarship uses to award full tuition coverage in the state.",
    uniqueTips: [
      "<strong class=\"text-slate-900\">Honors college admission starts at 3.5.</strong> Penn State Schreyer, UF Lombardi, Indiana Hutton, and most state honors colleges use 3.5 unweighted as the floor for sophomore-year admission. Honors admission unlocks priority registration, scholarships, and smaller classes.",
      "<strong class=\"text-slate-900\">NCAA D1 \"qualifier\" status from day one.</strong> A 3.5+ core-course GPA plus minimum SAT/ACT scores qualifies you as a full D1 qualifier — meaning full athletic and academic eligibility from freshman year. Below 3.0 starts triggering academic-redshirt or non-qualifier classifications.",
      "<strong class=\"text-slate-900\">ROTC competitive scholarships open at 3.5.</strong> The Army four-year ROTC scholarship's competitive cutoff has historically tracked around 3.7, but 3.5+ enters serious contention. Awards are worth $40K+ per year.",
      "<strong class=\"text-slate-900\">3.5+ transfer to UC system is real.</strong> The UC system uses 3.5 as a soft cutoff for guaranteed transfer-credit consideration. Most state flagships will admit a CC transfer with 3.5+ GPA across at least 30 transferable credit hours.",
    ],
    sourceUrl: "https://www2.ed.gov/about/offices/list/ope/oii/index.html",
  },
  {
    slug: "3-6",
    value: "3.6",
    numeric: 3.6,
    letter: "A-",
    percentage: "90-92%",
    percentile: "75th percentile of US high schoolers",
    verdict: "A 3.6 GPA is a solid A- — competitive for selective state schools and most private universities.",
    verdictLong: "A 3.6 GPA equals an A- letter grade. You're in the top 25% of US high school students. This GPA opens up selective state flagship admissions, most private universities, and competitive merit-aid programs.",
    collegeTier: "Selective state flagships, most private universities, honors colleges",
    ivyChance: "Reach",
    stateFlagshipChance: "Strong match",
    scholarshipImpact: "Meets 3.5+ threshold for competitive merit aid.",
    isGood: "good",
    primaryKw: "3.6 gpa",
    searchVolume: 6800,
    faqs: [
      { q: "Is a 3.6 GPA good?", a: "Yes — a 3.6 GPA is a solid A- and puts you in the top 25% of US high schoolers. It's competitive for selective state flagships, most private universities, and strong merit scholarships." },
      { q: "Is 3.6 gpa good in college?", a: "Yes. A 3.6 in college is well above the dean's list threshold at most schools and competitive for graduate school admission." },
      { q: "What is a 3.6 GPA in percentage?", a: "A 3.6 GPA equals approximately 90-92% on US grading scales, equivalent to an A- letter grade." },
    ],
  },
  {
    slug: "3-7",
    value: "3.7",
    numeric: 3.7,
    letter: "A-",
    percentage: "90-93%",
    percentile: "80th percentile of US high schoolers",
    verdict: "A 3.7 GPA is a high A- — competitive for top-50 private universities and most state flagships.",
    verdictLong: "A 3.7 GPA equals a high A-. You're in the top 20% of US high schoolers. This GPA opens up top-50 private universities, all state flagships including selective ones, and the strongest merit-aid programs.",
    collegeTier: "Top-50 private universities, all state flagships, honors colleges",
    ivyChance: "Reach (low-Ivies plausible)",
    stateFlagshipChance: "Strong match including top flagships",
    scholarshipImpact: "Competitive for top institutional merit aid.",
    isGood: "good",
    primaryKw: "3.7 gpa",
    searchVolume: 7700,
    faqs: [
      { q: "Is a 3.7 GPA good?", a: "Yes — a 3.7 GPA is a high A- and puts you in the top 20% of US high schoolers. It's competitive for top-50 private universities and selective state flagships." },
      { q: "Is 3.7 gpa good?", a: "Yes — it's the high A- range and considered \"very good\" by college admissions standards. With strong test scores and extracurriculars, it can be competitive even at lower-tier Ivies." },
      { q: "Is a 3.7 GPA good in high school?", a: "Yes — a 3.7 in high school is excellent. It's competitive for most private universities including top-50 ranked schools and clears all state flagship admission standards." },
      { q: "What is a 3.7 GPA in percentage?", a: "A 3.7 GPA equals approximately 90-93% on US grading scales — a high A-." },
    ],
  },
  {
    slug: "3-8",
    value: "3.8",
    numeric: 3.8,
    letter: "A",
    percentage: "92-95%",
    percentile: "Top 15% of US high schoolers",
    verdict: "A 3.8 GPA is a low A — competitive for top-25 universities and most Ivy-tier programs.",
    verdictLong: "A 3.8 GPA equals an A letter grade and puts you in the top 15% of US high schoolers. It's competitive for top-25 universities, including some Ivy-tier programs when paired with strong test scores and extracurriculars.",
    collegeTier: "Top-25 universities, selective Ivies achievable, all state flagships, top merit scholarship eligible",
    ivyChance: "Reach (strong applicants competitive)",
    stateFlagshipChance: "Auto-admit at most",
    scholarshipImpact: "Competitive for top institutional merit aid and named scholarships.",
    isGood: "good",
    primaryKw: "3.8 gpa",
    searchVolume: 7700,
    faqs: [
      { q: "Is a 3.8 GPA good?", a: "Yes — a 3.8 GPA is an A letter grade and puts you in the top 15% of US high schoolers. It's competitive for top-25 universities and selective programs at most colleges." },
      { q: "What is a 3.8 GPA in percentage?", a: "A 3.8 GPA equals approximately 92-95% on US grading scales, equivalent to an A letter grade." },
      { q: "Is a 3.8 GPA good in college?", a: "Yes. A 3.8 college GPA is excellent — it qualifies for top honors recognition and is highly competitive for graduate school admission, including selective programs." },
      { q: "What letter grade is a 3.8 GPA?", a: "A 3.8 GPA equals an A letter grade on the standard 4.0 scale." },
    ],
    indexed: true,
    intro:
      "A 3.8 GPA is competitive at most state flagships, strong at private liberal-arts colleges, and the practical floor for serious Ivy League applicants — though Ivy admits typically clear 3.9+ unweighted. It puts you in the top 10-12% of US high schoolers. The number gets you read by competitive admissions offices; whether you're admitted depends on rigor (AP/IB course count), essays, and how your school reports class rank.",
    realWorldExample:
      "Yale's Class of 2028 had a median unweighted GPA of 3.93. Stanford's was 3.96. A 3.8 unweighted with a 4.4+ weighted is right at the threshold where Ivy admission becomes mathematically plausible — not guaranteed, but in range with strong essays and test scores.",
    uniqueTips: [
      "<strong class=\"text-slate-900\">Course rigor matters more than the GPA itself.</strong> A 3.8 with 8+ APs reads stronger than a 4.0 with 2 APs. Top private colleges use AP/IB course count as the primary signal — the GPA is read in the context of available rigor.",
      "<strong class=\"text-slate-900\">3.8 unweighted converts to 4.4-4.7 weighted.</strong> At schools using the standard +1.0 AP weighting, your 3.8 with a normal AP load ends up at 4.4-4.7 weighted. When colleges ask for \"academic GPA,\" they usually mean weighted in core academic courses.",
      "<strong class=\"text-slate-900\">3.8+ unlocks the strongest state merit awards.</strong> Bright Futures (FL, full coverage at 3.5+ in-state), Cal Grant A (CA, 3.0+ but competitive at 3.8+), HOPE Zell Miller (GA, 3.7+), and Bright Futures Medallion variants — all reach the strongest tier at 3.8+.",
      "<strong class=\"text-slate-900\">Phi Beta Kappa pathway starts here.</strong> The PBK academic honor society for the liberal arts requires 3.75+ cumulative GPA at the qualifying college, with junior-year election typical. If college PBK is a goal, the 3.8 high school trajectory sets the baseline.",
    ],
    sourceUrl: "https://nces.ed.gov/fastfacts/display.asp?id=372",
  },
  {
    slug: "3-9",
    value: "3.9",
    numeric: 3.9,
    letter: "A",
    percentage: "93-96%",
    percentile: "Top 10% of US high schoolers",
    verdict: "A 3.9 GPA is a high A — competitive for top-20 universities and Ivy-tier programs.",
    verdictLong: "A 3.9 GPA equals a high A and puts you in the top 10% of US high schoolers. This GPA is highly competitive for top-20 universities, Ivy-tier programs, and the most selective merit scholarship programs in the country.",
    collegeTier: "Top-20 universities, Ivy-tier reach, all state flagships including honors, named-scholarship competitive",
    ivyChance: "Match for select Ivies, strong reach for top tier",
    stateFlagshipChance: "Auto-admit honors",
    scholarshipImpact: "Highly competitive for top named scholarships (Stamps, Park, Morehead).",
    isGood: "yes",
    primaryKw: "is a 3.9 gpa good",
    searchVolume: 2400,
    faqs: [
      { q: "Is a 3.9 GPA good?", a: "Yes — a 3.9 GPA is a high A and puts you in the top 10% of US high schoolers. It's highly competitive for top-20 universities and Ivy-tier programs." },
      { q: "Is 3.9 gpa good?", a: "Yes — it's near the maximum on the standard 4.0 scale and signals consistent A-level work across your transcript." },
      { q: "What is a 3.9 GPA in percentage?", a: "A 3.9 GPA equals approximately 93-96% on US grading scales — a high A letter grade." },
    ],
  },
  {
    slug: "4-0",
    value: "4.0",
    numeric: 4.0,
    letter: "A",
    percentage: "95-100%",
    percentile: "Top 5% of US high schoolers",
    verdict: "A 4.0 GPA is a perfect A average — the maximum on the standard unweighted scale.",
    verdictLong: "A 4.0 GPA is the maximum possible on the standard unweighted 4.0 scale. It means straight A's in every course taken. It's not common — only about 5% of US high schoolers graduate with a 4.0 unweighted, and even fewer maintain it across all four years.",
    collegeTier: "Competitive for every US college including Ivies (when paired with rigor and test scores)",
    ivyChance: "Strong match",
    stateFlagshipChance: "Auto-admit with honors invitation",
    scholarshipImpact: "Competitive for every named merit scholarship.",
    isGood: "yes",
    primaryKw: "is a 4.0 gpa good",
    searchVolume: 3900,
    faqs: [
      { q: "Is a 4.0 GPA good?", a: "Yes — a 4.0 GPA is the maximum possible on the standard unweighted scale. It puts you in the top 5% of US high schoolers and is competitive for every US college." },
      { q: "Is 4.0 gpa good?", a: "Yes — it's the highest unweighted GPA possible. To go higher (4.0+), you need weighted GPA from AP, Honors, or IB classes." },
      { q: "What is a 4.0 GPA in percentage?", a: "A 4.0 GPA equals approximately 95-100% on US grading scales — straight A's." },
      { q: "Whats a 4.0 GPA?", a: "A 4.0 GPA is straight A's on the 4.0 scale — the maximum unweighted GPA possible. Above 4.0 means weighted GPA from AP, Honors, or IB courses." },
    ],
    indexed: true,
    intro:
      "A 4.0 unweighted GPA means straight A's — the maximum end of the standard scale. It's a perfect academic record, but it's not unique enough on its own to guarantee Ivy League admission. The most selective schools see thousands of 4.0 applicants every year. What distinguishes admits is the combination: 4.0 unweighted plus 4.5-5.0 weighted, plus 8+ AP courses, plus standardized tests (SAT 1500+, ACT 34+), plus a meaningful extracurricular profile.",
    realWorldExample:
      "Harvard's Class of 2028 admitted students with a median unweighted GPA of 3.95 — meaning roughly half of admits were below 4.0. Among the 4.0 applicants, the admit rate was approximately 5%. A 4.0 is necessary, not sufficient, at the most selective schools.",
    uniqueTips: [
      "<strong class=\"text-slate-900\">Course rigor decides what 4.0 actually means.</strong> A 4.0 with light course rigor reads as \"honor roll at an easy school.\" Admissions officers compare your transcript to your school's available curriculum — if your school offers 12 APs and you took 2, the 4.0 means less than a 3.85 with 10 APs.",
      "<strong class=\"text-slate-900\">A+ grades can push weighted past 4.0.</strong> Most schools cap an A at 4.0 but allow A+ to count as 4.33. If your transcript shows A+ grades, that bumps weighted GPA above 4.0 even without AP weighting. Top colleges read both the transcript and the school profile to know which scale applies.",
      "<strong class=\"text-slate-900\">4.0 unlocks named merit aid at private schools.</strong> Full-tuition scholarships at private universities — Tulane Distinguished, Northeastern Honors, ASU President's, USC Trustee — often require 4.0+ to compete. Priority deadlines run in November, before regular admission decisions.",
      "<strong class=\"text-slate-900\">Take the B, don't take the W.</strong> The biggest mistake high-GPA students make is dropping a course mid-semester rather than taking a B. A W doesn't affect GPA, but admissions officers see it as risk-aversion. The B preserves the courses-taken signal admissions reads as effort.",
    ],
    sourceUrl: "https://www.collegeboard.org/membership/all-access/counseling-admissions-financial-aid-academic",
  },
  {
    slug: "4-2",
    value: "4.2",
    numeric: 4.2,
    letter: "A+ weighted",
    percentage: "95-100% weighted",
    percentile: "Top 5% (requires weighted scale)",
    verdict: "A 4.2 GPA is a weighted A+ — straight A's with AP/Honors course bonuses applied.",
    verdictLong: "A 4.2 GPA can only exist on a weighted scale. It means straight A's with about a third of your courses being AP, Honors, or IB (each adding +0.5 to +1.0 to the unweighted grade point). It's highly competitive for top-tier universities.",
    collegeTier: "Competitive for top-20 universities and Ivies",
    ivyChance: "Match",
    stateFlagshipChance: "Auto-admit with honors invitation",
    scholarshipImpact: "Highly competitive for named merit scholarships.",
    isGood: "yes",
    primaryKw: "4.2 gpa",
    searchVolume: 1100,
    faqs: [
      { q: "Is a 4.2 GPA good?", a: "Yes — a 4.2 weighted GPA means you've earned straight A's with a meaningful AP/Honors course load. It's highly competitive for top-tier universities." },
      { q: "Is a 4.2 GPA possible?", a: "Yes, but only on a weighted scale. The unweighted scale caps at 4.0. The weighted scale adds +0.5 for Honors and +1.0 for AP/IB, which is how GPAs above 4.0 are reached." },
    ],
  },
  {
    slug: "4-3",
    value: "4.3",
    numeric: 4.3,
    letter: "A+ weighted",
    percentage: "95-100% weighted",
    percentile: "Top 4% (requires weighted scale)",
    verdict: "A 4.3 GPA is a strong weighted A+ — competitive for Ivy and top-20 admissions.",
    verdictLong: "A 4.3 GPA can only exist on a weighted scale. It signals straight A's with about half your courses at AP, Honors, or IB level. It's the upper edge of what's competitive for Ivy-tier admissions.",
    collegeTier: "Competitive for Ivies and top-20 universities",
    ivyChance: "Match",
    stateFlagshipChance: "Auto-admit honors",
    scholarshipImpact: "Top-tier named scholarship competitive.",
    isGood: "yes",
    primaryKw: "is a 4.3 gpa good",
    searchVolume: 600,
    faqs: [
      { q: "Is a 4.3 GPA good?", a: "Yes — a 4.3 weighted GPA is excellent and competitive for Ivy and top-20 university admissions." },
    ],
  },
  {
    slug: "4-5",
    value: "4.5",
    numeric: 4.5,
    letter: "A+ weighted",
    percentage: "Straight A's with heavy AP load",
    percentile: "Top 3% (requires weighted scale)",
    verdict: "A 4.5 GPA is a high weighted A+ — typical of valedictorian candidates at AP-heavy schools.",
    verdictLong: "A 4.5 weighted GPA means straight A's with roughly half to two-thirds of your courses at AP, Honors, or IB level. It's typical of valedictorian-level students at competitive high schools and highly competitive for Ivy and top-20 admissions.",
    collegeTier: "Competitive for Ivies and top-20 universities",
    ivyChance: "Strong match",
    stateFlagshipChance: "Auto-admit honors with invitation",
    scholarshipImpact: "Top named-scholarship competitive (Stamps, Park, Morehead, Robertson).",
    isGood: "yes",
    primaryKw: "4.5 gpa",
    searchVolume: 1200,
    faqs: [
      { q: "Is a 4.5 GPA good?", a: "Yes — a 4.5 weighted GPA is excellent and typical of valedictorian-level students. It's highly competitive for Ivy and top-20 universities." },
      { q: "How do you get a 4.5 GPA?", a: "You earn a 4.5 weighted GPA by taking a heavy AP/Honors course load (about half to two-thirds of your classes) and earning straight A's. Your school's weighting scale determines the exact bonus per course." },
    ],
  },
  {
    slug: "3-25",
    value: "3.25",
    numeric: 3.25,
    letter: "B+",
    percentage: "85-87%",
    percentile: "60th percentile of US high schoolers",
    verdict: "A 3.25 GPA is a B+ average — sufficient for most state colleges and basic merit aid.",
    verdictLong: "A 3.25 GPA equals a B+ letter grade. You're in the 60th percentile of US high schoolers — slightly above the median. This GPA meets the 3.0+ threshold used by most state colleges and basic merit scholarships, while sitting just below the typical 3.5+ threshold for selective state flagships.",
    collegeTier: "Most state colleges, regional privates, some less-selective flagships",
    ivyChance: "Not realistic",
    stateFlagshipChance: "Match for less-selective flagships",
    scholarshipImpact: "Meets 3.0+ threshold for basic merit aid. Below 3.5+ threshold for stronger awards.",
    isGood: "good",
    primaryKw: "is a 3.25 gpa good",
    searchVolume: 600,
    faqs: [
      { q: "Is a 3.25 GPA good?", a: "A 3.25 GPA is a B+ average and sits above the national high school median. It meets admission at most state colleges and the 3.0 threshold for basic merit aid, though stronger schools and competitive scholarships typically expect 3.5+." },
      { q: "What letter grade is a 3.25 GPA?", a: "A 3.25 GPA equals a B+ letter grade, roughly 85-87% on US grading scales." },
      { q: "Is 3.25 GPA good in college?", a: "Yes — a 3.25 college GPA clears the 3.0 floor most graduate schools and competitive scholarships set, while comfortably exceeding the 2.0 minimum required to remain in good academic standing." },
    ],
  },
  {
    slug: "3-33",
    value: "3.33",
    numeric: 3.33,
    letter: "B+",
    percentage: "87-89%",
    percentile: "63rd percentile of US high schoolers",
    verdict: "A 3.33 GPA is a solid B+ — exact 3.33 = B+ on schools using third-point increments.",
    verdictLong: "A 3.33 GPA is the exact value B+ on schools that use third-point increments (A = 4.0, A- = 3.67, B+ = 3.33, B = 3.0, etc.). It puts you in the top 40% of US high schoolers and opens admission to most state flagships and competitive merit aid.",
    collegeTier: "Most state flagships, regional privates, NCAA eligible",
    ivyChance: "Reach (very selective)",
    stateFlagshipChance: "Match for most flagships",
    scholarshipImpact: "Meets 3.0+ requirements for competitive merit aid.",
    isGood: "good",
    primaryKw: "3.33 gpa",
    searchVolume: 600,
    faqs: [
      { q: "Is a 3.33 GPA good?", a: "Yes — a 3.33 GPA is a B+ average and puts you in the top 40% of US high schoolers. It's the exact value of B+ on the standard plus/minus 4.0 scale." },
      { q: "Is 3.33 a B+?", a: "Yes. The standard 4.0 scale with +/- grades sets B+ at exactly 3.33 grade points. Schools using the standard +/- scale will show a 3.33 cumulative as straight B+ work." },
    ],
  },
  {
    slug: "3-75",
    value: "3.75",
    numeric: 3.75,
    letter: "A-/A",
    percentage: "91-93%",
    percentile: "Top 18% of US high schoolers",
    verdict: "A 3.75 GPA sits between A- and A — competitive for top-30 universities and strong merit aid.",
    verdictLong: "A 3.75 GPA falls between A- (3.67) and A (4.0) on the standard +/- scale, putting you in the top 18% of US high schoolers. It's competitive for top-30 universities, all state flagships, and strong institutional merit aid programs.",
    collegeTier: "Top-30 private universities, all state flagships including selective, honors colleges",
    ivyChance: "Reach (low Ivies plausible)",
    stateFlagshipChance: "Strong match including top flagships",
    scholarshipImpact: "Competitive for strong institutional merit aid and many named scholarships.",
    isGood: "good",
    primaryKw: "3.75 gpa",
    searchVolume: 500,
    faqs: [
      { q: "Is a 3.75 GPA good?", a: "Yes — a 3.75 GPA puts you in the top 18% of US high schoolers and is competitive for top-30 private universities and selective state flagships." },
      { q: "Is 3.75 a good GPA in college?", a: "Yes. A 3.75 college GPA clears most graduate school admission floors comfortably and qualifies for the higher honors recognition at most schools (magna cum laude territory)." },
      { q: "What letter grade is a 3.75 GPA?", a: "A 3.75 GPA sits between A- (3.67) and A (4.0) on the standard +/- scale — closer to a clean A average." },
    ],
  },
];

export function getGpaScoreData(slug: string): GpaScoreData | undefined {
  return GPA_SCORE_DATA.find((d) => d.slug === slug);
}

export function getAllGpaSlugs(): string[] {
  return GPA_SCORE_DATA.map((d) => d.slug);
}
