// Auto-generated GPA score landing-page data table.
// One entry per GPA score (e.g. 3.8). Keys are dash slugs ("3-8").
// Source for tier rankings: NCES, College Board, US News admit-rate brackets.

export interface GpaScoreData {
  slug: string;             // "3-8" → URL /gpa/3-8
  value: string;            // "3.8"
  numeric: number;          // 3.8
  letter: string;           // "A-/A"
  percentage: string;       // "90-92%" range
  percentile: string;       // "Top 15% of high schoolers"
  verdict: string;          // 1-line plain-language verdict
  verdictLong: string;      // 2-3 sentence elaboration
  collegeTier: string;      // tier of schools accessible
  ivyChance: string;        // "Stretch" | "Reach" | "Match" etc
  stateFlagshipChance: string;
  scholarshipImpact: string;
  isGood: "yes" | "good" | "average" | "low" | "very-low";
  primaryKw: string;        // main target keyword (highest vol)
  searchVolume: number;     // monthly US volume from Ahrefs
  faqs: { q: string; a: string }[];
}

export const GPA_SCORE_DATA: GpaScoreData[] = [
  {
    slug: "1-0",
    value: "1.0",
    numeric: 1.0,
    letter: "D",
    percentage: "65%",
    percentile: "Bottom 5% of US high schoolers",
    verdict: "A 1.0 GPA is a D average — it's failing for most college and scholarship requirements.",
    verdictLong: "A 1.0 GPA equals straight D's on the 4.0 scale, putting you in the bottom 5% nationally. Most colleges, including community colleges, require at least a 2.0 cumulative GPA. Without intervention, students at this level often face academic dismissal or are pushed onto probation.",
    collegeTier: "Open-enrollment community colleges only, often with mandatory remedial coursework",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Disqualifies you from virtually all merit aid. Federal Pell Grant still available based on financial need.",
    isGood: "very-low",
    primaryKw: "1.0 gpa",
    searchVolume: 800,
    faqs: [
      { q: "Is a 1.0 GPA passing?", a: "A 1.0 GPA equals a D average. Technically a D is the lowest passing grade at most schools — but it usually does not meet course prerequisites or graduation requirements." },
      { q: "Can I raise a 1.0 GPA?", a: "Yes, but it requires earning A's in nearly every remaining class. Use the GPA Goal Calculator to see what's mathematically possible based on your credits earned and remaining." },
      { q: "What colleges accept a 1.0 GPA?", a: "Most four-year colleges require 2.0+. Open-enrollment community colleges sometimes admit students below 2.0 but place them in developmental courses first." },
    ],
  },
  {
    slug: "1-3",
    value: "1.3",
    numeric: 1.3,
    letter: "D+",
    percentage: "67-69%",
    percentile: "Bottom 7% of US high schoolers",
    verdict: "A 1.3 GPA is a D+ average — below the threshold to graduate from many high schools.",
    verdictLong: "A 1.3 GPA sits at D+ on the 4.0 scale. Most US high schools require at least a 2.0 to graduate, and four-year colleges almost always require 2.5+. At this level the focus should be on stopping the decline, then earning A's to lift the cumulative average.",
    collegeTier: "Community colleges with remedial pathways",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Disqualifies all merit aid. Need-based federal aid still available.",
    isGood: "very-low",
    primaryKw: "1.3 gpa",
    searchVolume: 500,
    faqs: [
      { q: "Is a 1.3 GPA recoverable?", a: "Yes, especially early in your academic career. The fewer credits you've earned, the easier each new grade moves the average. Check the math with our GPA Goal Calculator." },
      { q: "Will a 1.3 GPA keep me from graduating?", a: "Most US high schools require a 2.0 GPA to graduate. A 1.3 will not meet that bar — you'll need to raise it or enter a credit-recovery program." },
    ],
  },
  {
    slug: "1-7",
    value: "1.7",
    numeric: 1.7,
    letter: "C-",
    percentage: "70-72%",
    percentile: "Bottom 10% of US high schoolers",
    verdict: "A 1.7 GPA is a C- average — usually below the graduation threshold and almost all college admit minimums.",
    verdictLong: "A 1.7 GPA equates to a C- letter grade. While technically passing, it sits below the 2.0 minimum that most high schools require for graduation and that nearly every four-year college requires for admission.",
    collegeTier: "Community colleges, some open-enrollment four-years",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Most merit awards require 2.5+. Federal Pell Grant available regardless of GPA.",
    isGood: "low",
    primaryKw: "1.7 gpa",
    searchVolume: 800,
    faqs: [
      { q: "Can I get into college with a 1.7 GPA?", a: "Open-enrollment community colleges admit students at this level, often with developmental course placement. Selective four-year colleges typically require 2.5 or higher." },
      { q: "What's the fastest way to raise a 1.7 GPA?", a: "Three things matter: stop the decline, retake courses where your school allows grade replacement, and load up on courses you can confidently earn A's in." },
    ],
  },
  {
    slug: "1-8",
    value: "1.8",
    numeric: 1.8,
    letter: "C-",
    percentage: "72-73%",
    percentile: "Bottom 11% of US high schoolers",
    verdict: "A 1.8 GPA is a low C- — under the 2.0 floor most schools require to graduate or transfer.",
    verdictLong: "A 1.8 GPA falls in the C- range. It's only 0.2 points below the 2.0 minimum required by most high schools and four-year colleges, so a recovery is plausible with focused effort.",
    collegeTier: "Community colleges and some less-selective four-year schools",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Most scholarships require 2.5+ minimum. Pell Grant still based on need only.",
    isGood: "low",
    primaryKw: "1.8 gpa",
    searchVolume: 900,
    faqs: [
      { q: "Is a 1.8 GPA enough to graduate high school?", a: "Most US high schools require a 2.0 cumulative GPA to graduate. A 1.8 would typically need to be raised first." },
      { q: "How many A's do I need to raise a 1.8 GPA?", a: "Depends on how many credits you've already earned. Run the math on the GPA Goal Calculator with your current credits and target." },
    ],
  },
  {
    slug: "1-9",
    value: "1.9",
    numeric: 1.9,
    letter: "C-/C",
    percentage: "73-74%",
    percentile: "Bottom 13% of US high schoolers",
    verdict: "A 1.9 GPA is just below the standard 2.0 floor required by most colleges and many high schools.",
    verdictLong: "A 1.9 GPA equates to a low C. You're one-tenth of a point below the 2.0 cutoff that most high schools require for graduation and that almost all four-year colleges set as their minimum.",
    collegeTier: "Community colleges, some less-selective four-years",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Below most merit-aid thresholds (typically 2.5+). Need-based aid unaffected.",
    isGood: "low",
    primaryKw: "1.9 gpa",
    searchVolume: 800,
    faqs: [
      { q: "Can a 1.9 GPA become a 2.0 quickly?", a: "Yes — one strong semester of A's and B's can lift a 1.9 above 2.0, especially with fewer total credits earned. The exact number depends on your transcript size." },
    ],
  },
  {
    slug: "2-0",
    value: "2.0",
    numeric: 2.0,
    letter: "C",
    percentage: "73-76%",
    percentile: "Bottom 20% of US high schoolers",
    verdict: "A 2.0 GPA is a straight C average — the bare minimum to graduate high school and apply to college.",
    verdictLong: "A 2.0 GPA equals a C average and is the standard graduation requirement at most US high schools. It meets the minimum admission bar at most community colleges and a handful of four-year schools, but selective colleges and most merit scholarships expect higher.",
    collegeTier: "Community colleges, less-selective four-years, some state schools with conditional admit",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not possible",
    scholarshipImpact: "Doesn't meet most merit thresholds (typically 2.5-3.0+). Need-based aid available.",
    isGood: "low",
    primaryKw: "2.0 gpa",
    searchVolume: 4700,
    faqs: [
      { q: "Is a 2.0 GPA failing?", a: "No. A 2.0 GPA is a C average and is generally considered the minimum passing GPA for high school graduation and many college admission requirements." },
      { q: "Can I go to a 4-year college with a 2.0 GPA?", a: "Some less-selective four-year schools admit students at the 2.0 level. Most state flagships and selective colleges require 3.0 or higher." },
      { q: "What is a 2.0 GPA in percentage?", a: "A 2.0 GPA equates to roughly 73-76% on most US grading scales, equivalent to a C letter grade." },
    ],
  },
  {
    slug: "2-3",
    value: "2.3",
    numeric: 2.3,
    letter: "C+",
    percentage: "77-79%",
    percentile: "Bottom 22% of US high schoolers",
    verdict: "A 2.3 GPA is a C+ average — meets high school graduation requirements but is below the standard for most four-year colleges.",
    verdictLong: "A 2.3 GPA equals a C+ on the 4.0 scale. You're meeting high school graduation requirements but sitting below the 2.5-3.0 minimum that most state and private colleges expect from applicants.",
    collegeTier: "Community colleges, some state non-flagships, regional privates",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not realistic",
    scholarshipImpact: "Doesn't meet 2.5+ minimums for most merit scholarships. Pell and need-based aid available.",
    isGood: "low",
    primaryKw: "2.3 gpa",
    searchVolume: 1900,
    faqs: [
      { q: "Is a 2.3 GPA good?", a: "A 2.3 GPA is a C+ — passing, but below the level that opens up four-year college and scholarship options. Raising to 2.5-3.0 unlocks many more opportunities." },
      { q: "What is a 2.3 GPA?", a: "A 2.3 GPA equals a C+ letter grade, roughly 77-79% on most US grading scales. It meets graduation requirements at most high schools but is below the admit threshold of most four-year colleges." },
    ],
  },
  {
    slug: "2-4",
    value: "2.4",
    numeric: 2.4,
    letter: "C+",
    percentage: "77-79%",
    percentile: "Bottom 23% of US high schoolers",
    verdict: "A 2.4 GPA is a C+ average — usable for community college and some non-selective four-years.",
    verdictLong: "A 2.4 GPA is in the C+ range. It meets graduation requirements, opens up community college admission, and some less-selective four-year schools may accept you with a strong application or upward trend in grades.",
    collegeTier: "Community colleges, non-flagship state schools, some regional privates",
    ivyChance: "Not possible",
    stateFlagshipChance: "Not realistic",
    scholarshipImpact: "Below 2.5 merit threshold. Need-based aid available.",
    isGood: "low",
    primaryKw: "2.4 gpa letter grade",
    searchVolume: 500,
    faqs: [
      { q: "What letter grade is a 2.4 GPA?", a: "A 2.4 GPA equals a C+ letter grade on the standard 4.0 scale used by most US high schools and colleges." },
    ],
  },
  {
    slug: "2-5",
    value: "2.5",
    numeric: 2.5,
    letter: "B-/C+",
    percentage: "80-82%",
    percentile: "Bottom 25% of US high schoolers",
    verdict: "A 2.5 GPA is just at the B- line — meets the bar for many state colleges and basic merit awards.",
    verdictLong: "A 2.5 GPA equals a B-/C+ average. It crosses the threshold used by many state colleges for unconditional admission and the minimum for many institutional merit scholarships.",
    collegeTier: "Most state universities, community colleges, regional private colleges",
    ivyChance: "Not possible",
    stateFlagshipChance: "Below typical admit, possible with strong essays/extracurriculars",
    scholarshipImpact: "Meets the 2.5 floor for many basic merit awards.",
    isGood: "average",
    primaryKw: "2.5 gpa",
    searchVolume: 4300,
    faqs: [
      { q: "Is a 2.5 GPA good?", a: "A 2.5 GPA is the standard B- floor — it meets minimum admission at most state colleges and basic merit-aid thresholds, but it's below the 3.0+ that competitive programs expect." },
      { q: "What letter grade is a 2.5 GPA?", a: "A 2.5 GPA sits between C+ and B-, equivalent to roughly 80-82% on most US grading scales." },
      { q: "What is a 2.5 GPA in percentage?", a: "A 2.5 GPA equals approximately 80-82% on US grading scales — a low B-." },
    ],
  },
  {
    slug: "2-6",
    value: "2.6",
    numeric: 2.6,
    letter: "B-",
    percentage: "80-82%",
    percentile: "Bottom 28% of US high schoolers",
    verdict: "A 2.6 GPA is a low B- — opens up state college admissions but is below selective-school cutoffs.",
    verdictLong: "A 2.6 GPA is in the low B- range. It meets the admission bar at most state colleges and many regional private universities. Selective and flagship schools typically expect 3.0 or higher.",
    collegeTier: "Most state universities and regional privates",
    ivyChance: "Not possible",
    stateFlagshipChance: "Below typical, possible with strong upward trend",
    scholarshipImpact: "Meets most institutional 2.5 minimums.",
    isGood: "average",
    primaryKw: "2.6 gpa letter grade",
    searchVolume: 700,
    faqs: [
      { q: "What letter grade is a 2.6 GPA?", a: "A 2.6 GPA equals a B- letter grade, roughly 80-82% on most US grading scales." },
    ],
  },
  {
    slug: "2-7",
    value: "2.7",
    numeric: 2.7,
    letter: "B-",
    percentage: "80-83%",
    percentile: "Bottom 30% of US high schoolers",
    verdict: "A 2.7 GPA is a solid B- — sufficient for most state colleges and many merit-aid thresholds.",
    verdictLong: "A 2.7 GPA is a B- average. It comfortably clears admission at most state schools and many regional private universities, and meets the 2.5+ minimum for most basic merit scholarships.",
    collegeTier: "Most state universities, regional privates, some larger publics",
    ivyChance: "Not possible",
    stateFlagshipChance: "Match for less-selective flagships, below for top flagships",
    scholarshipImpact: "Meets most institutional 2.5+ thresholds.",
    isGood: "average",
    primaryKw: "2.7 gpa",
    searchVolume: 3500,
    faqs: [
      { q: "Is a 2.7 GPA good?", a: "A 2.7 GPA is a B- average — solid for state college admission and most basic merit scholarships. It's below the 3.0+ threshold that more selective schools expect." },
      { q: "What is a 2.7 GPA?", a: "A 2.7 GPA equals a B- letter grade, roughly 80-83% on US grading scales." },
    ],
  },
  {
    slug: "2-8",
    value: "2.8",
    numeric: 2.8,
    letter: "B-",
    percentage: "83-86%",
    percentile: "Bottom 35% of US high schoolers",
    verdict: "A 2.8 GPA is a high B- — opens up most state colleges and unlocks more merit-aid options.",
    verdictLong: "A 2.8 GPA equals a high B-. It opens admission to most state universities, regional privates, and many less-selective flagship state schools. It clears the 2.5 minimum for basic scholarships but falls short of the 3.0+ that competitive merit aid requires.",
    collegeTier: "Most state colleges, regional privates, some less-selective flagships",
    ivyChance: "Not possible",
    stateFlagshipChance: "Match for less-selective flagships",
    scholarshipImpact: "Meets 2.5 floor, just below 3.0 for stronger awards.",
    isGood: "average",
    primaryKw: "2.8 gpa",
    searchVolume: 4300,
    faqs: [
      { q: "Is a 2.8 GPA good?", a: "A 2.8 GPA is a high B- — strong enough for most state college admissions and basic merit scholarships, but below the 3.0+ threshold that competitive programs expect." },
      { q: "Is a 2.8 GPA good in high school?", a: "It's slightly below average for US high schoolers. It's enough to graduate and apply to most state schools, but selective colleges and competitive scholarships typically want 3.0 or higher." },
      { q: "What is a 2.8 GPA in percentage?", a: "A 2.8 GPA equals approximately 83-86% on US grading scales, equivalent to a B- letter grade." },
    ],
  },
  {
    slug: "2-9",
    value: "2.9",
    numeric: 2.9,
    letter: "B-/B",
    percentage: "83-86%",
    percentile: "Bottom 38% of US high schoolers",
    verdict: "A 2.9 GPA is just below the B threshold — within reach of strong scholarships and selective state schools.",
    verdictLong: "A 2.9 GPA is a high B-, just one point below the 3.0 line that many scholarships and selective colleges set as their floor. A strong final semester can push you above it.",
    collegeTier: "Most state colleges, regional privates, some flagships",
    ivyChance: "Not realistic",
    stateFlagshipChance: "Match for less-selective flagships",
    scholarshipImpact: "Just below the 3.0 cutoff for competitive merit aid.",
    isGood: "average",
    primaryKw: "2.9 gpa letter grade",
    searchVolume: 700,
    faqs: [
      { q: "What letter grade is a 2.9 GPA?", a: "A 2.9 GPA is a high B-, equivalent to roughly 83-86% on US grading scales." },
    ],
  },
  {
    slug: "3-0",
    value: "3.0",
    numeric: 3.0,
    letter: "B",
    percentage: "83-86%",
    percentile: "Around average for US high schoolers (50th percentile)",
    verdict: "A 3.0 GPA is a B average — the standard \"good\" GPA that opens up most state colleges and many scholarships.",
    verdictLong: "A 3.0 GPA equals a B average and sits at the national high school median. It's the threshold most state colleges, NCAA athletic eligibility, and many merit scholarships use as their minimum. Selective and elite colleges expect 3.5 or higher.",
    collegeTier: "Most state universities (including some flagships), regional privates, NCAA eligible",
    ivyChance: "Not realistic for top tier",
    stateFlagshipChance: "Match for many state flagships",
    scholarshipImpact: "Meets 3.0 floor used by most institutional merit awards.",
    isGood: "good",
    primaryKw: "3.0 gpa",
    searchVolume: 9300,
    faqs: [
      { q: "Is a 3.0 GPA good?", a: "Yes — a 3.0 GPA is a B average and is generally considered \"good.\" It meets admission requirements at most state colleges and the threshold for most merit-aid programs." },
      { q: "What is a 3.0 GPA in letter grade?", a: "A 3.0 GPA equals a B letter grade on the standard 4.0 scale." },
      { q: "Is a 3.0 GPA good in college?", a: "In college a 3.0 is a B average — solid and above the 2.0 minimum almost all programs require to stay in good standing. For graduate school admission, however, you typically want 3.0-3.5 minimum." },
      { q: "What is a 3.0 GPA in percentage?", a: "A 3.0 GPA equals approximately 83-86% on most US grading scales, equivalent to a B letter grade." },
    ],
  },
  {
    slug: "3-1",
    value: "3.1",
    numeric: 3.1,
    letter: "B",
    percentage: "84-86%",
    percentile: "53rd percentile of US high schoolers",
    verdict: "A 3.1 GPA is a B average — above national median, meets most state college and basic merit-aid thresholds.",
    verdictLong: "A 3.1 GPA is a low-to-mid B. It clears the 3.0 threshold most state colleges and basic merit scholarships use as their minimum, while sitting just above the national high school median.",
    collegeTier: "Most state universities, regional privates, NCAA eligible",
    ivyChance: "Not realistic for top tier",
    stateFlagshipChance: "Match for many state flagships, reach for top flagships",
    scholarshipImpact: "Meets 3.0 floor used by most institutional merit awards.",
    isGood: "good",
    primaryKw: "3.1 gpa",
    searchVolume: 2800,
    faqs: [
      { q: "Is a 3.1 GPA good?", a: "Yes — a 3.1 GPA is a B average and slightly above the national high school median. It meets admission requirements at most state colleges and the 3.0 threshold used by most merit-aid programs." },
      { q: "What is a 3.1 GPA?", a: "A 3.1 GPA equals a B letter grade, roughly 84-86% on most US grading scales." },
    ],
  },
  {
    slug: "3-2",
    value: "3.2",
    numeric: 3.2,
    letter: "B",
    percentage: "84-86%",
    percentile: "57th percentile of US high schoolers",
    verdict: "A 3.2 GPA is a solid B — opens up most state colleges, many private universities, and competitive merit-aid programs.",
    verdictLong: "A 3.2 GPA sits comfortably in the B range. It meets the 3.0+ threshold used by most state colleges, private universities, and basic merit scholarships, while putting you above the US high school median.",
    collegeTier: "Most state colleges including flagships, regional privates, NCAA eligible",
    ivyChance: "Reach (very selective)",
    stateFlagshipChance: "Match for most state flagships",
    scholarshipImpact: "Meets 3.0+ threshold for competitive merit aid.",
    isGood: "good",
    primaryKw: "3.2 gpa letter grade",
    searchVolume: 1200,
    faqs: [
      { q: "What letter grade is a 3.2 GPA?", a: "A 3.2 GPA equals a B letter grade, roughly 84-86% on US grading scales." },
      { q: "Is a 3.2 GPA good in college?", a: "Yes — a 3.2 GPA in college clears the 3.0 floor most graduate schools and competitive scholarships use, while comfortably exceeding the 2.0 minimum required to stay in good academic standing." },
    ],
  },
  {
    slug: "3-3",
    value: "3.3",
    numeric: 3.3,
    letter: "B+",
    percentage: "87-89%",
    percentile: "60th percentile of US high schoolers",
    verdict: "A 3.3 GPA is a B+ average — solid for most state flagships and competitive merit aid.",
    verdictLong: "A 3.3 GPA equals a B+ letter grade. It's above the national high school median and opens up most state flagship universities, many private colleges, and competitive merit scholarship programs.",
    collegeTier: "Most state flagships, regional privates, many mid-tier privates",
    ivyChance: "Reach (very selective)",
    stateFlagshipChance: "Match for most flagships",
    scholarshipImpact: "Meets 3.0+ requirements for competitive merit aid.",
    isGood: "good",
    primaryKw: "3.3 gpa",
    searchVolume: 5500,
    faqs: [
      { q: "Is a 3.3 GPA good?", a: "Yes — a 3.3 GPA is a B+ average and sits comfortably above the national high school median. It opens up most state flagships and meets the threshold for competitive merit aid." },
      { q: "Is 3.3 a good gpa?", a: "Yes. A 3.3 is a B+ — solid for most state flagship universities, competitive scholarships, and many private colleges." },
      { q: "What is a 3.3 GPA in percentage?", a: "A 3.3 GPA equals approximately 87-89% on US grading scales, equivalent to a B+." },
    ],
  },
  {
    slug: "3-4",
    value: "3.4",
    numeric: 3.4,
    letter: "B+",
    percentage: "87-89%",
    percentile: "65th percentile of US high schoolers",
    verdict: "A 3.4 GPA is a high B+ — above national median, opens most state flagships and competitive scholarships.",
    verdictLong: "A 3.4 GPA equals a high B+ letter grade. You're in the top 35% of US high school students. This GPA opens admission to most state flagship universities, many private colleges, and competitive merit-aid programs.",
    collegeTier: "Most state flagships, many private universities, NCAA eligible",
    ivyChance: "Reach",
    stateFlagshipChance: "Match for most flagships",
    scholarshipImpact: "Meets 3.0-3.5 thresholds for stronger institutional merit aid.",
    isGood: "good",
    primaryKw: "3.4 gpa",
    searchVolume: 6400,
    faqs: [
      { q: "Is a 3.4 GPA good?", a: "Yes — a 3.4 GPA is a high B+ and puts you in the top 35% of US high schoolers. It opens up most state flagship universities and competitive merit aid." },
      { q: "Is a 3.4 GPA good in high school?", a: "Yes. A 3.4 in high school is above the national median and well-positioned for state flagship admission. Selective private colleges typically expect 3.7+." },
      { q: "What letter grade is a 3.4 GPA?", a: "A 3.4 GPA equals a B+ letter grade, roughly 87-89% on US grading scales." },
    ],
  },
  {
    slug: "3-5",
    value: "3.5",
    numeric: 3.5,
    letter: "A-",
    percentage: "90-93%",
    percentile: "70th percentile of US high schoolers",
    verdict: "A 3.5 GPA is an A- average — the standard \"dean's list\" GPA and the threshold for many selective colleges.",
    verdictLong: "A 3.5 GPA equals an A- letter grade. It's the dean's list standard at most colleges and the typical admit GPA for less-selective private universities. Many merit scholarships set 3.5 as their minimum threshold.",
    collegeTier: "State flagships, many private universities, public honors colleges, NCAA Division I eligible",
    ivyChance: "Reach",
    stateFlagshipChance: "Strong match",
    scholarshipImpact: "Meets 3.5 threshold for stronger merit aid and most honors program admission.",
    isGood: "good",
    primaryKw: "is a 3.5 gpa good",
    searchVolume: 6100,
    faqs: [
      { q: "Is a 3.5 GPA good?", a: "Yes — a 3.5 GPA is an A- average and considered \"very good.\" It's the dean's list standard and the threshold for many competitive merit scholarships." },
      { q: "Is a 3.5 GPA good in college?", a: "Yes. In college a 3.5 GPA is excellent — it qualifies for dean's list at most schools and clears the bar for most graduate school admissions." },
      { q: "Is a 3.5 GPA good in high school?", a: "Yes. A 3.5 GPA in high school puts you in the top 30% nationally and opens admission to most state flagships and many private universities. Top-tier colleges (Ivies, MIT, Stanford) typically expect 3.8+." },
      { q: "What is a 3.5 GPA?", a: "A 3.5 GPA equals an A- letter grade, roughly 90-93% on US grading scales." },
    ],
  },
  {
    slug: "3-6",
    value: "3.6",
    numeric: 3.6,
    letter: "A-",
    percentage: "90-92%",
    percentile: "75th percentile of US high schoolers",
    verdict: "A 3.6 GPA is a solid A- — competitive for selective state schools and most private universities.",
    verdictLong: "A 3.6 GPA equals an A- letter grade. You're in the top 25% of US high school students. This GPA opens up selective state flagship admissions, most private universities, and competitive merit-aid programs.",
    collegeTier: "Selective state flagships, most private universities, honors colleges",
    ivyChance: "Reach",
    stateFlagshipChance: "Strong match",
    scholarshipImpact: "Meets 3.5+ threshold for competitive merit aid.",
    isGood: "good",
    primaryKw: "3.6 gpa",
    searchVolume: 6800,
    faqs: [
      { q: "Is a 3.6 GPA good?", a: "Yes — a 3.6 GPA is a solid A- and puts you in the top 25% of US high schoolers. It's competitive for selective state flagships, most private universities, and strong merit scholarships." },
      { q: "Is 3.6 gpa good in college?", a: "Yes. A 3.6 in college is well above the dean's list threshold at most schools and competitive for graduate school admission." },
      { q: "What is a 3.6 GPA in percentage?", a: "A 3.6 GPA equals approximately 90-92% on US grading scales, equivalent to an A- letter grade." },
    ],
  },
  {
    slug: "3-7",
    value: "3.7",
    numeric: 3.7,
    letter: "A-",
    percentage: "90-93%",
    percentile: "80th percentile of US high schoolers",
    verdict: "A 3.7 GPA is a high A- — competitive for top-50 private universities and most state flagships.",
    verdictLong: "A 3.7 GPA equals a high A-. You're in the top 20% of US high schoolers. This GPA opens up top-50 private universities, all state flagships including selective ones, and the strongest merit-aid programs.",
    collegeTier: "Top-50 private universities, all state flagships, honors colleges",
    ivyChance: "Reach (low-Ivies plausible)",
    stateFlagshipChance: "Strong match including top flagships",
    scholarshipImpact: "Competitive for top institutional merit aid.",
    isGood: "good",
    primaryKw: "3.7 gpa",
    searchVolume: 7700,
    faqs: [
      { q: "Is a 3.7 GPA good?", a: "Yes — a 3.7 GPA is a high A- and puts you in the top 20% of US high schoolers. It's competitive for top-50 private universities and selective state flagships." },
      { q: "Is 3.7 gpa good?", a: "Yes — it's the high A- range and considered \"very good\" by college admissions standards. With strong test scores and extracurriculars, it can be competitive even at lower-tier Ivies." },
      { q: "Is a 3.7 GPA good in high school?", a: "Yes — a 3.7 in high school is excellent. It's competitive for most private universities including top-50 ranked schools and clears all state flagship admission standards." },
      { q: "What is a 3.7 GPA in percentage?", a: "A 3.7 GPA equals approximately 90-93% on US grading scales — a high A-." },
    ],
  },
  {
    slug: "3-8",
    value: "3.8",
    numeric: 3.8,
    letter: "A",
    percentage: "92-95%",
    percentile: "Top 15% of US high schoolers",
    verdict: "A 3.8 GPA is a low A — competitive for top-25 universities and most Ivy-tier programs.",
    verdictLong: "A 3.8 GPA equals an A letter grade and puts you in the top 15% of US high schoolers. It's competitive for top-25 universities, including some Ivy-tier programs when paired with strong test scores and extracurriculars.",
    collegeTier: "Top-25 universities, selective Ivies achievable, all state flagships, top merit scholarship eligible",
    ivyChance: "Reach (strong applicants competitive)",
    stateFlagshipChance: "Auto-admit at most",
    scholarshipImpact: "Competitive for top institutional merit aid and named scholarships.",
    isGood: "good",
    primaryKw: "3.8 gpa",
    searchVolume: 7700,
    faqs: [
      { q: "Is a 3.8 GPA good?", a: "Yes — a 3.8 GPA is an A letter grade and puts you in the top 15% of US high schoolers. It's competitive for top-25 universities and selective programs at most colleges." },
      { q: "What is a 3.8 GPA in percentage?", a: "A 3.8 GPA equals approximately 92-95% on US grading scales, equivalent to an A letter grade." },
      { q: "Is a 3.8 GPA good in college?", a: "Yes. A 3.8 college GPA is excellent — it qualifies for top honors recognition and is highly competitive for graduate school admission, including selective programs." },
      { q: "What letter grade is a 3.8 GPA?", a: "A 3.8 GPA equals an A letter grade on the standard 4.0 scale." },
    ],
  },
  {
    slug: "3-9",
    value: "3.9",
    numeric: 3.9,
    letter: "A",
    percentage: "93-96%",
    percentile: "Top 10% of US high schoolers",
    verdict: "A 3.9 GPA is a high A — competitive for top-20 universities and Ivy-tier programs.",
    verdictLong: "A 3.9 GPA equals a high A and puts you in the top 10% of US high schoolers. This GPA is highly competitive for top-20 universities, Ivy-tier programs, and the most selective merit scholarship programs in the country.",
    collegeTier: "Top-20 universities, Ivy-tier reach, all state flagships including honors, named-scholarship competitive",
    ivyChance: "Match for select Ivies, strong reach for top tier",
    stateFlagshipChance: "Auto-admit honors",
    scholarshipImpact: "Highly competitive for top named scholarships (Stamps, Park, Morehead).",
    isGood: "yes",
    primaryKw: "is a 3.9 gpa good",
    searchVolume: 2400,
    faqs: [
      { q: "Is a 3.9 GPA good?", a: "Yes — a 3.9 GPA is a high A and puts you in the top 10% of US high schoolers. It's highly competitive for top-20 universities and Ivy-tier programs." },
      { q: "Is 3.9 gpa good?", a: "Yes — it's near the maximum on the standard 4.0 scale and signals consistent A-level work across your transcript." },
      { q: "What is a 3.9 GPA in percentage?", a: "A 3.9 GPA equals approximately 93-96% on US grading scales — a high A letter grade." },
    ],
  },
  {
    slug: "4-0",
    value: "4.0",
    numeric: 4.0,
    letter: "A",
    percentage: "95-100%",
    percentile: "Top 5% of US high schoolers",
    verdict: "A 4.0 GPA is a perfect A average — the maximum on the standard unweighted scale.",
    verdictLong: "A 4.0 GPA is the maximum possible on the standard unweighted 4.0 scale. It means straight A's in every course taken. It's not common — only about 5% of US high schoolers graduate with a 4.0 unweighted, and even fewer maintain it across all four years.",
    collegeTier: "Competitive for every US college including Ivies (when paired with rigor and test scores)",
    ivyChance: "Strong match",
    stateFlagshipChance: "Auto-admit with honors invitation",
    scholarshipImpact: "Competitive for every named merit scholarship.",
    isGood: "yes",
    primaryKw: "is a 4.0 gpa good",
    searchVolume: 3900,
    faqs: [
      { q: "Is a 4.0 GPA good?", a: "Yes — a 4.0 GPA is the maximum possible on the standard unweighted scale. It puts you in the top 5% of US high schoolers and is competitive for every US college." },
      { q: "Is 4.0 gpa good?", a: "Yes — it's the highest unweighted GPA possible. To go higher (4.0+), you need weighted GPA from AP, Honors, or IB classes." },
      { q: "What is a 4.0 GPA in percentage?", a: "A 4.0 GPA equals approximately 95-100% on US grading scales — straight A's." },
      { q: "Whats a 4.0 GPA?", a: "A 4.0 GPA is straight A's on the 4.0 scale — the maximum unweighted GPA possible. Above 4.0 means weighted GPA from AP, Honors, or IB courses." },
    ],
  },
  {
    slug: "4-2",
    value: "4.2",
    numeric: 4.2,
    letter: "A+ weighted",
    percentage: "95-100% weighted",
    percentile: "Top 5% (requires weighted scale)",
    verdict: "A 4.2 GPA is a weighted A+ — straight A's with AP/Honors course bonuses applied.",
    verdictLong: "A 4.2 GPA can only exist on a weighted scale. It means straight A's with about a third of your courses being AP, Honors, or IB (each adding +0.5 to +1.0 to the unweighted grade point). It's highly competitive for top-tier universities.",
    collegeTier: "Competitive for top-20 universities and Ivies",
    ivyChance: "Match",
    stateFlagshipChance: "Auto-admit with honors invitation",
    scholarshipImpact: "Highly competitive for named merit scholarships.",
    isGood: "yes",
    primaryKw: "4.2 gpa",
    searchVolume: 1100,
    faqs: [
      { q: "Is a 4.2 GPA good?", a: "Yes — a 4.2 weighted GPA means you've earned straight A's with a meaningful AP/Honors course load. It's highly competitive for top-tier universities." },
      { q: "Is a 4.2 GPA possible?", a: "Yes, but only on a weighted scale. The unweighted scale caps at 4.0. The weighted scale adds +0.5 for Honors and +1.0 for AP/IB, which is how GPAs above 4.0 are reached." },
    ],
  },
  {
    slug: "4-3",
    value: "4.3",
    numeric: 4.3,
    letter: "A+ weighted",
    percentage: "95-100% weighted",
    percentile: "Top 4% (requires weighted scale)",
    verdict: "A 4.3 GPA is a strong weighted A+ — competitive for Ivy and top-20 admissions.",
    verdictLong: "A 4.3 GPA can only exist on a weighted scale. It signals straight A's with about half your courses at AP, Honors, or IB level. It's the upper edge of what's competitive for Ivy-tier admissions.",
    collegeTier: "Competitive for Ivies and top-20 universities",
    ivyChance: "Match",
    stateFlagshipChance: "Auto-admit honors",
    scholarshipImpact: "Top-tier named scholarship competitive.",
    isGood: "yes",
    primaryKw: "is a 4.3 gpa good",
    searchVolume: 600,
    faqs: [
      { q: "Is a 4.3 GPA good?", a: "Yes — a 4.3 weighted GPA is excellent and competitive for Ivy and top-20 university admissions." },
    ],
  },
  {
    slug: "4-5",
    value: "4.5",
    numeric: 4.5,
    letter: "A+ weighted",
    percentage: "Straight A's with heavy AP load",
    percentile: "Top 3% (requires weighted scale)",
    verdict: "A 4.5 GPA is a high weighted A+ — typical of valedictorian candidates at AP-heavy schools.",
    verdictLong: "A 4.5 weighted GPA means straight A's with roughly half to two-thirds of your courses at AP, Honors, or IB level. It's typical of valedictorian-level students at competitive high schools and highly competitive for Ivy and top-20 admissions.",
    collegeTier: "Competitive for Ivies and top-20 universities",
    ivyChance: "Strong match",
    stateFlagshipChance: "Auto-admit honors with invitation",
    scholarshipImpact: "Top named-scholarship competitive (Stamps, Park, Morehead, Robertson).",
    isGood: "yes",
    primaryKw: "4.5 gpa",
    searchVolume: 1200,
    faqs: [
      { q: "Is a 4.5 GPA good?", a: "Yes — a 4.5 weighted GPA is excellent and typical of valedictorian-level students. It's highly competitive for Ivy and top-20 universities." },
      { q: "How do you get a 4.5 GPA?", a: "You earn a 4.5 weighted GPA by taking a heavy AP/Honors course load (about half to two-thirds of your classes) and earning straight A's. Your school's weighting scale determines the exact bonus per course." },
    ],
  },
];

export function getGpaScoreData(slug: string): GpaScoreData | undefined {
  return GPA_SCORE_DATA.find((d) => d.slug === slug);
}

export function getAllGpaSlugs(): string[] {
  return GPA_SCORE_DATA.map((d) => d.slug);
}
