// University GPA calculator pages — top 50 by search volume (vol >= 150).
// Source: Ahrefs paid export 2026-06-01 for US keywords.

export interface UniData {
  slug: string;          // url segment: "uf"
  abbr: string;          // display abbr: "UF"
  fullName: string;      // full official name
  shortName: string;     // common short reference
  state: string;
  type: "public" | "private";
  scaleNote: string;     // grading scale note
  weightingPolicy: string; // whether uni weights grades for admission
  admitRange: string;    // mid-50% admit GPA range
  honorsGpa: string;     // GPA for honors / dean's list
  goodStandingGpa: string; // GPA for good academic standing
  searchVolume: number;  // monthly US volume (sum of uni variants)
}

export const UNIS: UniData[] = [
  {
    slug: "uf",
    abbr: "UF",
    fullName: "University of Florida",
    shortName: "Florida",
    state: "FL",
    type: "public",
    scaleNote: "Standard 4.0 scale. A = 4.0, A- = 3.67, B+ = 3.33, etc.",
    weightingPolicy: "UF recalculates GPA from your transcript using core academic courses only and adds standard weight (+1.0) for AP/IB/AICE and +0.5 for Honors.",
    admitRange: "4.4 - 4.6 weighted (recalculated)",
    honorsGpa: "3.75+ for Dean's List",
    goodStandingGpa: "2.0 (below = academic probation)",
    searchVolume: 6600,
  },
  {
    slug: "asu",
    abbr: "ASU",
    fullName: "Arizona State University",
    shortName: "Arizona State",
    state: "AZ",
    type: "public",
    scaleNote: "Standard 4.33 scale. A+ = 4.33 (counted as 4.0 for most uses), A = 4.0.",
    weightingPolicy: "ASU does not weight GPA for admission. The application uses your unweighted GPA on the 4.0 scale.",
    admitRange: "3.5 - 3.8 unweighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 3500,
  },
  {
    slug: "purdue",
    abbr: "Purdue",
    fullName: "Purdue University",
    shortName: "Purdue",
    state: "IN",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/− grades (A = 4.0, A- = 3.7, B+ = 3.3).",
    weightingPolicy: "Purdue admission uses your high school GPA as reported. Honors and AP weighting is reviewed contextually alongside course rigor.",
    admitRange: "3.5 - 3.9 (West Lafayette campus)",
    honorsGpa: "3.5+ for Semester Honors",
    goodStandingGpa: "2.0",
    searchVolume: 3000,
  },
  {
    slug: "uw-madison",
    abbr: "UW-Madison",
    fullName: "University of Wisconsin-Madison",
    shortName: "Wisconsin",
    state: "WI",
    type: "public",
    scaleNote: "Standard 4.0 scale. A = 4.0, AB = 3.5, B = 3.0, BC = 2.5 (the school uses AB and BC as midpoint grades).",
    weightingPolicy: "Wisconsin uses unweighted GPA but considers course rigor separately. Honors and AP courses are factored into the admissions decision.",
    admitRange: "3.8 - 4.0 unweighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1900,
  },
  {
    slug: "ut",
    abbr: "UT",
    fullName: "University of Texas at Austin",
    shortName: "UT Austin",
    state: "TX",
    type: "public",
    scaleNote: "Standard 4.0 scale. A = 4.0, A- = 3.67, B+ = 3.33, etc.",
    weightingPolicy: "UT Austin uses your high school class rank as the primary admission factor (automatic admission for top 6% of Texas public school students). GPA is reviewed but secondary to rank.",
    admitRange: "3.7 - 4.0 (3.85 average)",
    honorsGpa: "3.5+ for College Scholar",
    goodStandingGpa: "2.0",
    searchVolume: 1800,
  },
  {
    slug: "rutgers",
    abbr: "Rutgers",
    fullName: "Rutgers University-New Brunswick",
    shortName: "Rutgers",
    state: "NJ",
    type: "public",
    scaleNote: "4.0 scale. A = 4.0, B+ = 3.5, B = 3.0, C+ = 2.5 (no A- or B-).",
    weightingPolicy: "Rutgers uses unweighted and weighted GPA together. Weighted gives small additional consideration for honors and AP work.",
    admitRange: "3.5 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1700,
  },
  {
    slug: "ucsd",
    abbr: "UCSD",
    fullName: "University of California, San Diego",
    shortName: "UC San Diego",
    state: "CA",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/− grades.",
    weightingPolicy: "UC uses a capped weighted GPA on grades earned in approved A-G courses from 10th and 11th grade only. Weighting is +1.0 for UC-honors-approved, AP, and IB classes up to a cap of 8 semesters.",
    admitRange: "4.13 - 4.32 UC-weighted",
    honorsGpa: "3.5+ for Provost's Honors",
    goodStandingGpa: "2.0",
    searchVolume: 1600,
  },
  {
    slug: "tamu",
    abbr: "TAMU",
    fullName: "Texas A&M University",
    shortName: "Texas A&M",
    state: "TX",
    type: "public",
    scaleNote: "Standard 4.0 scale. A = 4.0, B = 3.0, C = 2.0 (no +/− affect GPA).",
    weightingPolicy: "Texas A&M considers both rank and GPA. Honors and AP rigor is reviewed in the holistic decision.",
    admitRange: "3.6 - 4.0",
    honorsGpa: "3.5+ for Dean's Honor Roll",
    goodStandingGpa: "2.0",
    searchVolume: 1500,
  },
  {
    slug: "osu",
    abbr: "OSU",
    fullName: "The Ohio State University",
    shortName: "Ohio State",
    state: "OH",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Ohio State uses your school-reported GPA. Course rigor is considered alongside the number.",
    admitRange: "3.7 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1500,
  },
  {
    slug: "iu",
    abbr: "IU",
    fullName: "Indiana University Bloomington",
    shortName: "Indiana",
    state: "IN",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "IU admission considers your school GPA and class rank. AP/IB rigor is reviewed in context.",
    admitRange: "3.6 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1300,
  },
  {
    slug: "uiuc",
    abbr: "UIUC",
    fullName: "University of Illinois Urbana-Champaign",
    shortName: "Illinois",
    state: "IL",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "UIUC uses self-reported high school GPA. Course rigor matters for admissions decisions, particularly for engineering and business programs.",
    admitRange: "3.6 - 4.0 (3.85 average)",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1300,
  },
  {
    slug: "utd",
    abbr: "UTD",
    fullName: "University of Texas at Dallas",
    shortName: "UT Dallas",
    state: "TX",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "UTD admission uses an assured admission GPA formula combining class rank, GPA, and test scores. Honors and AP rigor is considered.",
    admitRange: "3.5 - 4.0",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1300,
  },
  {
    slug: "uta",
    abbr: "UTA",
    fullName: "University of Texas at Arlington",
    shortName: "UT Arlington",
    state: "TX",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "UTA uses GPA and rank for assured admission. AP/honors rigor reviewed alongside.",
    admitRange: "3.2 - 3.8",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1200,
  },
  {
    slug: "jmu",
    abbr: "JMU",
    fullName: "James Madison University",
    shortName: "James Madison",
    state: "VA",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "JMU considers both weighted and unweighted GPA. AP, IB, and dual-enrollment add bonus weight.",
    admitRange: "3.5 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1150,
  },
  {
    slug: "berkeley",
    abbr: "UC Berkeley",
    fullName: "University of California, Berkeley",
    shortName: "Berkeley",
    state: "CA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "UC system uses capped weighted GPA on 10th-11th grade A-G coursework, with +1.0 for UC-approved honors/AP/IB classes (max 8 semesters).",
    admitRange: "4.27 - 4.49 UC-weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1150,
  },
  {
    slug: "fsu",
    abbr: "FSU",
    fullName: "Florida State University",
    shortName: "Florida State",
    state: "FL",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "FSU recalculates GPA using core academic courses with +1.0 for AP/IB and +0.5 for Honors. Similar policy to UF.",
    admitRange: "4.0 - 4.4 weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1150,
  },
  {
    slug: "usf",
    abbr: "USF",
    fullName: "University of South Florida",
    shortName: "South Florida",
    state: "FL",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "USF recalculates GPA using core academic courses with weighted bonus for AP/IB/Honors.",
    admitRange: "3.8 - 4.2 weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1000,
  },
  {
    slug: "uw",
    abbr: "UW",
    fullName: "University of Washington",
    shortName: "Washington",
    state: "WA",
    type: "public",
    scaleNote: "Standard 4.0 scale with 0.1 increments (UW uses precise decimals, e.g. 3.7, 3.8, 3.9).",
    weightingPolicy: "UW considers your school's reported GPA. Holistic review weighs course rigor alongside the number.",
    admitRange: "3.75 - 3.95",
    honorsGpa: "3.5+ for Annual Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1000,
  },
  {
    slug: "tcu",
    abbr: "TCU",
    fullName: "Texas Christian University",
    shortName: "TCU",
    state: "TX",
    type: "private",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "TCU reviews weighted and unweighted GPA in holistic admissions.",
    admitRange: "3.5 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 900,
  },
  {
    slug: "nyu",
    abbr: "NYU",
    fullName: "New York University",
    shortName: "NYU",
    state: "NY",
    type: "private",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "NYU uses holistic review. School GPA reviewed alongside course rigor and other factors.",
    admitRange: "3.7 - 4.0",
    honorsGpa: "3.65+ for Dean's List (varies by school)",
    goodStandingGpa: "2.0",
    searchVolume: 900,
  },
  {
    slug: "csu",
    abbr: "CSU",
    fullName: "California State University system",
    shortName: "Cal State",
    state: "CA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "CSU uses an eligibility index combining GPA and test scores. Some campuses recalculate weighted GPA with +1.0 for honors/AP.",
    admitRange: "3.0 - 3.8 (varies by campus)",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 850,
  },
  {
    slug: "byu",
    abbr: "BYU",
    fullName: "Brigham Young University",
    shortName: "BYU",
    state: "UT",
    type: "private",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "BYU reviews weighted and unweighted GPA with course rigor consideration. Seminary participation also reviewed.",
    admitRange: "3.7 - 4.0",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 850,
  },
  {
    slug: "umd",
    abbr: "UMD",
    fullName: "University of Maryland, College Park",
    shortName: "Maryland",
    state: "MD",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Maryland uses a recalculated GPA based on core academic subjects. AP and IB receive additional weight.",
    admitRange: "3.9 - 4.3 weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 750,
  },
  {
    slug: "gmu",
    abbr: "GMU",
    fullName: "George Mason University",
    shortName: "George Mason",
    state: "VA",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "GMU reviews both weighted and unweighted GPA from the high school transcript.",
    admitRange: "3.4 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 750,
  },
  {
    slug: "pitt",
    abbr: "Pitt",
    fullName: "University of Pittsburgh",
    shortName: "Pitt",
    state: "PA",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Pitt uses school-reported GPA in holistic review with course rigor.",
    admitRange: "3.7 - 4.1 weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 700,
  },
  {
    slug: "ucsb",
    abbr: "UCSB",
    fullName: "University of California, Santa Barbara",
    shortName: "UC Santa Barbara",
    state: "CA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "Uses UC capped weighted GPA formula (+1.0 for UC-approved honors/AP/IB, max 8 semesters, 10th-11th grade only).",
    admitRange: "4.17 - 4.31 UC-weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 650,
  },
  {
    slug: "umich",
    abbr: "UMich",
    fullName: "University of Michigan",
    shortName: "Michigan",
    state: "MI",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Michigan uses unweighted GPA but factors course rigor heavily into admissions decisions.",
    admitRange: "3.9 - 4.0 unweighted",
    honorsGpa: "3.5+ for Dean's List (varies by school)",
    goodStandingGpa: "2.0",
    searchVolume: 650,
  },
  {
    slug: "columbia",
    abbr: "Columbia",
    fullName: "Columbia University",
    shortName: "Columbia",
    state: "NY",
    type: "private",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Columbia uses holistic admissions. School GPA reviewed alongside course rigor, recommendations, and essays.",
    admitRange: "3.9 - 4.0 unweighted",
    honorsGpa: "3.6+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 600,
  },
  {
    slug: "vcu",
    abbr: "VCU",
    fullName: "Virginia Commonwealth University",
    shortName: "VCU",
    state: "VA",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "VCU reviews both weighted and unweighted GPA in holistic admissions.",
    admitRange: "3.3 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 600,
  },
  {
    slug: "ttu",
    abbr: "TTU",
    fullName: "Texas Tech University",
    shortName: "Texas Tech",
    state: "TX",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "TTU uses assured admission via class rank and GPA combinations.",
    admitRange: "3.3 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 600,
  },
  {
    slug: "smu",
    abbr: "SMU",
    fullName: "Southern Methodist University",
    shortName: "SMU",
    state: "TX",
    type: "private",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "SMU uses holistic admissions. Weighted GPA and course rigor reviewed together.",
    admitRange: "3.6 - 4.0",
    honorsGpa: "3.4+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 570,
  },
  {
    slug: "cornell",
    abbr: "Cornell",
    fullName: "Cornell University",
    shortName: "Cornell",
    state: "NY",
    type: "private",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Cornell holistic review considers GPA, rigor, and school context. Schools-within-Cornell vary in selectivity.",
    admitRange: "3.9 - 4.0 unweighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 550,
  },
  {
    slug: "csuf",
    abbr: "CSUF",
    fullName: "California State University, Fullerton",
    shortName: "Cal State Fullerton",
    state: "CA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "CSU Fullerton uses the CSU eligibility index with capped weighted GPA.",
    admitRange: "3.2 - 3.7",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 500,
  },
  {
    slug: "fiu",
    abbr: "FIU",
    fullName: "Florida International University",
    shortName: "FIU",
    state: "FL",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "FIU recalculates GPA using core academic courses with +1.0 for AP/IB and +0.5 for Honors.",
    admitRange: "3.5 - 4.0 weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 500,
  },
  {
    slug: "psu",
    abbr: "Penn State",
    fullName: "Pennsylvania State University",
    shortName: "Penn State",
    state: "PA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "Penn State uses school-reported GPA in holistic review.",
    admitRange: "3.5 - 4.0",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 500,
  },
  {
    slug: "vt",
    abbr: "VT",
    fullName: "Virginia Tech",
    shortName: "Virginia Tech",
    state: "VA",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Virginia Tech reviews both weighted and unweighted GPA.",
    admitRange: "3.8 - 4.3 weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 450,
  },
  {
    slug: "ku",
    abbr: "KU",
    fullName: "University of Kansas",
    shortName: "Kansas",
    state: "KS",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "KU uses school-reported GPA. Course rigor reviewed alongside.",
    admitRange: "3.4 - 3.9",
    honorsGpa: "3.5+ for Honor Roll",
    goodStandingGpa: "2.0",
    searchVolume: 450,
  },
  {
    slug: "usc",
    abbr: "USC",
    fullName: "University of Southern California",
    shortName: "USC",
    state: "CA",
    type: "private",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "USC reviews GPA in context of course rigor, school profile, and recommendations.",
    admitRange: "3.85 - 4.0 unweighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 440,
  },
  {
    slug: "baylor",
    abbr: "Baylor",
    fullName: "Baylor University",
    shortName: "Baylor",
    state: "TX",
    type: "private",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Baylor reviews weighted GPA and course rigor in holistic admissions.",
    admitRange: "3.6 - 4.0",
    honorsGpa: "3.7+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 400,
  },
  {
    slug: "sdsu",
    abbr: "SDSU",
    fullName: "San Diego State University",
    shortName: "SDSU",
    state: "CA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "SDSU uses CSU eligibility index with capped weighted GPA.",
    admitRange: "3.6 - 4.0 weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 400,
  },
  {
    slug: "cal-poly",
    abbr: "Cal Poly",
    fullName: "California Polytechnic State University, San Luis Obispo",
    shortName: "Cal Poly SLO",
    state: "CA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "Cal Poly uses a Multi-Criteria Admission formula with weighted GPA, course rigor, and major-specific factors.",
    admitRange: "3.8 - 4.2 weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 380,
  },
  {
    slug: "wsu",
    abbr: "WSU",
    fullName: "Washington State University",
    shortName: "Washington State",
    state: "WA",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "WSU uses an Academic Index combining GPA and test scores.",
    admitRange: "3.4 - 3.9",
    honorsGpa: "3.5+ for President's Honor Roll",
    goodStandingGpa: "2.0",
    searchVolume: 370,
  },
  {
    slug: "utsa",
    abbr: "UTSA",
    fullName: "University of Texas at San Antonio",
    shortName: "UTSA",
    state: "TX",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "UTSA uses GPA and rank for admission. Honors/AP rigor reviewed alongside.",
    admitRange: "3.3 - 3.8",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 350,
  },
  {
    slug: "ucla",
    abbr: "UCLA",
    fullName: "University of California, Los Angeles",
    shortName: "UCLA",
    state: "CA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "UCLA uses UC capped weighted GPA (+1.0 for UC-approved honors/AP/IB, max 8 semesters, 10th-11th grade only).",
    admitRange: "4.31 - 4.50 UC-weighted",
    honorsGpa: "3.7+ for Dean's Honor List",
    goodStandingGpa: "2.0",
    searchVolume: 350,
  },
  {
    slug: "unc",
    abbr: "UNC",
    fullName: "University of North Carolina at Chapel Hill",
    shortName: "UNC",
    state: "NC",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "UNC uses recalculated weighted GPA. AP/IB courses receive +1.0, honors +0.5.",
    admitRange: "4.36 - 4.79 weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 350,
  },
  {
    slug: "uci",
    abbr: "UCI",
    fullName: "University of California, Irvine",
    shortName: "UC Irvine",
    state: "CA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "Uses UC capped weighted GPA formula.",
    admitRange: "4.0 - 4.27 UC-weighted",
    honorsGpa: "3.5+ for Dean's Honor List",
    goodStandingGpa: "2.0",
    searchVolume: 330,
  },
  {
    slug: "sjsu",
    abbr: "SJSU",
    fullName: "San Jose State University",
    shortName: "SJSU",
    state: "CA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "SJSU uses CSU eligibility index with capped weighted GPA.",
    admitRange: "3.3 - 3.8 weighted",
    honorsGpa: "3.5+ for Dean's Scholar List",
    goodStandingGpa: "2.0",
    searchVolume: 320,
  },
  {
    slug: "ua",
    abbr: "UA",
    fullName: "University of Alabama",
    shortName: "Alabama",
    state: "AL",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "Alabama uses school-reported GPA. AP/honors rigor considered.",
    admitRange: "3.7 - 4.2",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 320,
  },
  {
    slug: "msu",
    abbr: "MSU",
    fullName: "Michigan State University",
    shortName: "Michigan State",
    state: "MI",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "MSU uses school-reported GPA with course rigor considered.",
    admitRange: "3.5 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 300,
  },
  {
    slug: "kent-state",
    abbr: "Kent State",
    fullName: "Kent State University",
    shortName: "Kent State",
    state: "OH",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Kent State reviews school-reported GPA.",
    admitRange: "3.2 - 3.7",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 300,
  },
  {
    slug: "lsu",
    abbr: "LSU",
    fullName: "Louisiana State University",
    shortName: "LSU",
    state: "LA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "LSU uses school-reported GPA and TOPS Core curriculum GPA for in-state admission decisions. AP/Honors rigor reviewed alongside.",
    admitRange: "3.4 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1500,
  },
  {
    slug: "lsac",
    abbr: "LSAC",
    fullName: "Law School Admission Council (CAS GPA)",
    shortName: "LSAC",
    state: "US",
    type: "private",
    scaleNote: "LSAC uses the CAS (Credential Assembly Service) GPA on a standardized 4.33 scale. A+ = 4.33, A = 4.0, A- = 3.67, etc. Every grade you ever received in undergrad is included, even retakes — repeated courses are NOT replaced.",
    weightingPolicy: "LSAC recalculates every applicant's undergraduate GPA from their transcripts using the standard 4.33 scale. Pass/fail grades, withdrawals, and grade replacements are normalized to LSAC's conventions. The resulting CAS GPA — not your school's reported GPA — is what law schools see.",
    admitRange: "Top 14 law schools: 3.7 - 3.9 CAS GPA",
    honorsGpa: "3.5+ for most law school merit scholarships",
    goodStandingGpa: "2.0 (varies by law school)",
    searchVolume: 1400,
  },
  {
    slug: "uh",
    abbr: "UH",
    fullName: "University of Houston",
    shortName: "Houston",
    state: "TX",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "UH uses school-reported GPA + rank for assured admission. AP/honors rigor considered.",
    admitRange: "3.3 - 3.8",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1100,
  },
  {
    slug: "uva",
    abbr: "UVA",
    fullName: "University of Virginia",
    shortName: "UVA",
    state: "VA",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "UVA uses school-reported GPA with strong consideration of course rigor in holistic admissions.",
    admitRange: "4.0 - 4.3 weighted",
    honorsGpa: "3.4+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 1000,
  },
  {
    slug: "uga",
    abbr: "UGA",
    fullName: "University of Georgia",
    shortName: "Georgia",
    state: "GA",
    type: "public",
    scaleNote: "Standard 4.0 scale.",
    weightingPolicy: "UGA recalculates GPA on academic core courses with bonus weight for AP/IB/dual-enrollment.",
    admitRange: "3.9 - 4.3 weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 800,
  },
  {
    slug: "clemson",
    abbr: "Clemson",
    fullName: "Clemson University",
    shortName: "Clemson",
    state: "SC",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Clemson reviews weighted and unweighted GPA along with course rigor.",
    admitRange: "3.7 - 4.2 weighted",
    honorsGpa: "3.5+ for President's List",
    goodStandingGpa: "2.0",
    searchVolume: 900,
  },
  {
    slug: "amcas",
    abbr: "AMCAS",
    fullName: "American Medical College Application Service (AMCAS GPA)",
    shortName: "AMCAS",
    state: "US",
    type: "private",
    scaleNote: "AMCAS recalculates undergraduate GPA on a standard 4.0 scale and separates Science GPA (BCPM: Biology, Chemistry, Physics, Math) from non-Science GPA. Every grade from every transcript counts — including retakes (both attempts).",
    weightingPolicy: "AMCAS does NOT replace grades for retaken courses (unlike most undergrad institutions). Both attempts are averaged into the AMCAS GPA. AP credit is excluded from AMCAS GPA. The recalculated GPA is what medical schools use, not your school's reported GPA.",
    admitRange: "Top med schools: 3.8 - 3.9 AMCAS GPA + 3.8+ Science GPA",
    honorsGpa: "3.7+ AMCAS GPA for competitive medical school admission",
    goodStandingGpa: "3.0 (typical pre-med floor)",
    searchVolume: 800,
  },
  {
    slug: "caspa",
    abbr: "CASPA",
    fullName: "Centralized Application Service for Physician Assistants (CASPA GPA)",
    shortName: "CASPA",
    state: "US",
    type: "private",
    scaleNote: "CASPA recalculates undergraduate GPA on a 4.0 scale and reports multiple GPAs: overall, science, BCP, non-science, and post-baccalaureate.",
    weightingPolicy: "CASPA averages all grades from all transcripts — retakes do not replace original grades. AP credit is generally not included. The CASPA GPA, not your school GPA, is what PA programs see.",
    admitRange: "PA programs: 3.5 - 3.7 CASPA GPA",
    honorsGpa: "3.6+ for competitive PA program admission",
    goodStandingGpa: "3.0 (typical pre-PA floor)",
    searchVolume: 800,
  },
  {
    slug: "uic",
    abbr: "UIC",
    fullName: "University of Illinois Chicago",
    shortName: "UIC",
    state: "IL",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "UIC reviews school-reported GPA with course rigor in holistic admissions.",
    admitRange: "3.4 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 700,
  },
  {
    slug: "unl",
    abbr: "UNL",
    fullName: "University of Nebraska-Lincoln",
    shortName: "Nebraska",
    state: "NE",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "UNL uses school-reported GPA and class rank in admission decisions.",
    admitRange: "3.4 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 700,
  },
  {
    slug: "uky",
    abbr: "UKY",
    fullName: "University of Kentucky",
    shortName: "Kentucky",
    state: "KY",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "UKY uses school-reported GPA. AP/honors rigor considered.",
    admitRange: "3.3 - 3.8",
    honorsGpa: "3.6+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 600,
  },
  {
    slug: "auburn",
    abbr: "Auburn",
    fullName: "Auburn University",
    shortName: "Auburn",
    state: "AL",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Auburn uses school-reported GPA + test scores in admission decisions.",
    admitRange: "3.5 - 4.1",
    honorsGpa: "3.4+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 600,
  },
  {
    slug: "uiowa",
    abbr: "UIowa",
    fullName: "University of Iowa",
    shortName: "Iowa",
    state: "IA",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Iowa uses Regent Admission Index — formula combining GPA, rank, and test scores.",
    admitRange: "3.5 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 500,
  },
  {
    slug: "mizzou",
    abbr: "Mizzou",
    fullName: "University of Missouri",
    shortName: "Mizzou",
    state: "MO",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "Mizzou uses school-reported GPA + ACT/SAT. Holistic for borderline applicants.",
    admitRange: "3.4 - 3.9",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 700,
  },
  {
    slug: "uofsc",
    abbr: "UofSC",
    fullName: "University of South Carolina",
    shortName: "South Carolina",
    state: "SC",
    type: "public",
    scaleNote: "Standard 4.0 scale with +/−.",
    weightingPolicy: "UofSC reviews weighted GPA, course rigor, and test scores.",
    admitRange: "3.6 - 4.2 weighted",
    honorsGpa: "3.5+ for Dean's List",
    goodStandingGpa: "2.0",
    searchVolume: 900,
  },
];

export function getUni(slug: string): UniData | undefined {
  return UNIS.find((u) => u.slug === slug);
}
